- docker-compose.yml
- packages/providers/codegen.json
- packages/providers/src/operations.graphql
- packages/providers/src/operations.ts
- packages/providers/src/provider.test.ts
- packages/providers/src/provider.ts
- packages/providers/src/script.ts
- packages/providers/src/transaction-request/input.ts
- packages/providers/src/util.ts
- packages/transactions/src/coders/input.test.ts
- packages/transactions/src/coders/input.ts
- packages/transactions/src/coders/utxo-id.test.ts
- packages/transactions/src/coders/utxo-id.ts
A bunch of changes mostly for UtxoId support.
Resolves #101
> Upgrade to fuel-core:v0.2.1

- packages/typechain-target-fuels/src/codegen/index.ts
- packages/typechain-target-fuels/src/index.ts
> Refactor on typechain

- README.md
> Remove phrase on readme

- .gitignore
- package-lock.json
- packages/wallet/package.json
- packages/wallet/src/signer.ts
- packages/wallet/src/types/GenerateOptions.ts
- packages/wallet/src/wallet.test.ts
- packages/wallet/src/wallet.ts
- Adds, Generate random wallet;
- Adds the possibility to pass an extra entropy;
- `Wallet.generate(options)` open for optional configuration like `generate from mnemonic`;
- Lock `@ethersproject/random@5.5.1` to avoid non-intentional updates.
https://github.com/ethereumjs/ethereumjs-wallet/blob/master/src/index.ts
https://github.com/crypto-browserify/randombytes
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues
https://github.com/ethers-io/ethers.js/blob/master/packages/random
https://nodejs.org/api/crypto.html#cryptorandombytessize-callback
The `randomBytes` is critical to have a secure source of entropy. Because of this, I have chosen the package `@ethersproject/random`. It has a similar implementation from other modules/wallets. Where the idea is to; Use …
> Generate random Wallet

- packages/abi-coder/src/fragments/fragment.ts
- packages/abi-coder/src/fragments/function-fragment.ts
- packages/abi-coder/src/interface.test.ts
- packages/abi-coder/src/interface.ts
- packages/contract/src/contract.test.ts
- packages/providers/src/provider.test.ts
> feat!: Update interface and fragment to ignore gas, amount and color in

- docs/packages/fuel-ts-wallet/classes/Signer.md
- docs/packages/fuel-ts-wallet/classes/Wallet.md
- docs/packages/fuel-ts-wallet/index.md
- docs/packages/fuel-ts-wallet/interfaces/internal-GenerateOptions.md
- docs/packages/fuel-ts-wallet/namespaces/internal.md
- packages/wallet/src/signer.ts
- Generate docs for `Wallet.generate()` and `Signature.generatePrivateKey()`
- Fix some lint warnings on doc comments.
Refs.: #121
> Docs for Wallet.generate

- package-lock.json
- packages/wallet/package.json
- Move `@fuels/testcases` from `dependencies` to `devDependencies`.
> fix: move testcases to dev dependency

- packages/providers/src/provider.ts
- Add `CoinStatus` on `Coin` data output.
- Exports `CoinStatus` enum from Provider.
> Add CoinStatus

- .releaserc.json
- packages/fuels/package.json
Updated the commit analyzer to only do patch/minor semver bumps.
The plan is to add tags and then run CI to be `0.3.x`
> Release fix

- .github/workflows/sematic-release.yaml
> fix: setup-node@v2 now creates the .npmrc

- .github/workflows/sematic-release.yaml
> Update npm8 on action

- packages/contract/src/call-test-contract/call-test-contract.test.ts
- packages/contract/src/storage-test-contract/storage-test-contract.test.ts
- Move contract test to inside contract folder.
> chore: move test to contract folder

- packages/providers/src/operations.graphql
- packages/providers/src/provider.ts
- Add method to query Contract info `bytecode` on `provider`.
> feat: add get contract on provider

- packages/providers/fuel-core-schema.graphql
- packages/providers/src/operations.graphql
- packages/providers/src/provider.ts
- packages/wallet/src/wallet.ts
Adds new balance APIs on Provider using fuel-core's new GQL APIs. (Instead of fetching all coins.)
Also adds a `getBalance` API to Wallet.
> Balance APIs

- packages/wallet/src/transfer.test.ts
- packages/wallet/src/wallet.ts
Pass TX params to transfer
```
gasLimit, gasPrice, bytePrice, maturity
```
> feat: optional tx params

- packages/contract/src/contract-factory.test.ts
- packages/contract/src/contract-factory.ts
- packages/contract/src/index.ts
> feat: add options on deployContract

- README.md
> chore: add docs for `forc:update`

- README.md
See: https://github.com/FuelLabs/fuels-ts/pull/311#discussion_r887375655
> chore: remove signs from shell commands in readme

- packages/contract/src/call-test-contract/call-test-contract.test.ts
- packages/contract/src/contract.ts
- packages/wallet/src/wallet.ts
Add `simulate` call on contract.
cc @luizstacio
> feat!: simulate calls

- package.json
- pnpm-lock.yaml
- scripts/utils/changePackages.ts
I was getting 
adding the angular changelog seems to fix it
Also, update the package json update script to ignore directories like `forc`
> fix: add angular-changelog and check for fuels-ts package.json

- packages/contract/src/call-test-contract/Forc.lock
- packages/contract/src/contract-call-script/Forc.lock
- packages/contract/src/storage-test-contract/Forc.lock
- packages/contract/src/token-test-contract/token_abi/Forc.lock
- packages/contract/src/token-test-contract/token_contract/Forc.lock
- packages/contract/src/token-test-contract/token_contract/src/main.sw
- packages/example-contract/Forc.lock
- packages/forc-bin/package.json
- packages/script/src/call-test-script/Forc.lock
- scripts/utils/changePackages.ts
Updating `forc`
Can someone confirm `force_transfer` -> `force_transfer_to_contract` is correct?
> chore: update forc and refactor

- packages/contract/src/call-test-contract/Forc.lock
- packages/contract/src/contract-call-script/Forc.lock
- packages/contract/src/storage-test-contract/Forc.lock
- packages/contract/src/storage-test-contract/src/main.sw
- packages/contract/src/token-test-contract/token_abi/Forc.lock
- packages/contract/src/token-test-contract/token_contract/Forc.lock
- packages/example-contract/Forc.lock
- packages/forc-bin/package.json
- packages/script/src/call-test-script/Forc.lock
> chore: forc update 0.16

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- .github/workflows/publish-npm-master.yaml
- package.json
Remove the coverage command and go back to the default test run.  We should use https://github.com/marketplace/actions/jest-coverage-comment-action instead
> fix: clean services after tests

- .changeset/nice-lemons-love.md
- packages/contract/src/__test__/call-test-contract/Forc.lock
- packages/contract/src/__test__/storage-test-contract/Forc.lock
- packages/contract/src/__test__/token-test-contract/token_abi/Forc.lock
- packages/contract/src/__test__/token-test-contract/token_contract/Forc.lock
- packages/contract/src/contracts/multicall/Forc.lock
- packages/contract/src/contracts/multicall/src/buf.sw
- packages/contract/src/contracts/multicall/src/main.sw
- packages/example-contract/Forc.lock
- packages/example-contract/out/debug/example-contract-abi.json
- packages/forc-bin/package.json
- packages/predicate/src/predicate.test.ts
- packages/providers/src/provider.test.ts
- packages/script/src/call-test-script/Forc.lock
- services/fuel-core/Dockerfile
Upgrading to sway 0.18.1
Closes #399
> feat: upgrade to sway 0.18.1

- .changeset/tough-spiders-trade.md
- .github/actions/ci-setup/action.yaml
- package.json
- packages/contract/src/__test__/call-test-contract/call-test-contract.test.ts
- packages/forc-bin/package.json
- pnpm-lock.yaml
- turbo.json
- fix `pnpm build` broken when running first time after download repo in linux environment (including CI)
- run `forc-bin` build before other packages
Fix #408
> fix: run forc-bin build before other packages

- .changeset/cold-geckos-tickle.md
- packages/contract/src/__test__/contract.test.ts
Added(back) this test after the compiler bug got fixed
> fix: update test after compiler update

- docs/QUICKSTART.md
> docs: update QUICKSTART.md with updated forc deploy instructions

- .changeset/thirty-planes-laugh.md
- packages/abi-coder/src/index.ts
- packages/contract/src/index.ts
- packages/contract/src/scripts.ts
- packages/transactions/src/coders/input.ts
- packages/transactions/src/coders/output.ts
- packages/transactions/src/coders/receipt.ts
- packages/transactions/src/coders/transaction.ts
- packages/typechain-target-fuels/package.json
- Fix some imports and exports
- Add exports for types `FunctionInvocationScope` and `MultiCallInvocationScope`
> fix: exports and imports

- docs/QUICKSTART.md
> feat: add path on fuel-core run command to avoid collisions

- .changeset/dry-readers-smell.md
- packages/contract/src/__test__/token-test-contract/token_contract/src/main.sw
- packages/forc-bin/package.json
Updating to the new version of forc
> fix: update forc 0.25.0

- .changeset/violet-tips-brake.md
- packages/providers/package.json
- pnpm-lock.yaml
Although I followed the [docs](https://github.com/FuelLabs/fuels-ts/blob/master/docs/CONTRIBUTING.md#using-linked-packages), I couldn't link my local `fuels-ts` on other projects.
Because of this, I could not fully validate this PR upfront, but it's pretty simple, and I believe it does the job.
> chore: upgrading `graphql-request` package, fixing source-map warnings

- .changeset/great-mugs-retire.md
- .eslintrc.js
- packages/wallet-manager/src/types.ts
- packages/wallet-manager/src/wallet-manager.test.ts
- packages/wallet-manager/src/wallet-manager.ts
Add a new method on the wallet-manager to export the vault.
> feat: export vault

- .changeset/large-zoos-work.md
Fix decoding/encoding order of transaction Mint
creating this PR because need a changeset patch to release new version
> chore: bump version(fix decoding)

- .changeset/sixty-bugs-ring.md
- packages/abi-typegen/README.md
- packages/abi-typegen/package.json
- packages/abi-typegen/src/cli.test.ts
- packages/abi-typegen/src/cli.ts
- packages/abi-typegen/src/runTypegen.test.ts
- packages/abi-typegen/src/runTypegen.ts
> fix: typegen globals expansion

- .changeset/stale-students-happen.md
- packages/address/tsup.config.ts
- packages/math/tsup.config.ts
- packages/program/tsup.config.ts
- packages/transactions/tsup.config.ts
- packages/wallet/tsup.config.ts
> fix: adding missing `tsup` settings

- .changeset/new-islands-drive.md
- apps/docs/package.json
Fixes new Docs workspace version from `1.0.0` to `0.37.1`
> fix: docs workspace version

- .github/workflows/pr-release.yaml
> fix: filtering only first regex match in workflow

- .changeset/sour-emus-reflect.md
- apps/docs-snippets/src/guide/contracts/read-only-calls.test.ts
- apps/docs/src/guide/contracts/read-only-calls.md
- packages/program/src/functions/base-invocation-scope.ts
- packages/program/src/types.ts
- packages/script/src/script-invocation-scope.ts
> feat: deprecate tx funding call option

- jest.base.config.ts
- jest.browser.config.ts
- jest.node.config.ts
- package.json
- packages/abi-typegen/src/temp/index.browser.test.ts
- packages/abi-typegen/src/temp/index.node.test.ts
- packages/abi-typegen/src/temp/index.test.ts
- packages/abi-typegen/src/temp/index.ts
- scripts/get-test-files.sh
Brainstorming an alternative approach to segment tests running in:
- https://github.com/FuelLabs/fuels-ts/pull/1182
> chore: implement find/grep script for test files

- .changeset/rich-dryers-do.md
- packages/program/src/contract-call-script.ts
- packages/wallet/src/account.ts
- packages/wallet/src/utils.test.ts
- packages/wallet/src/utils.ts
> fix: await init wasm

- .changeset/rich-tools-shake.md
- packages/fuel-gauge/src/contract.test.ts
- packages/program/src/errors.ts
- Close https://github.com/FuelLabs/fuels-ts/issues/1245
> fix: `ScriptResultDecoderError` on dry run calls

- .changeset/rich-clocks-wait.md
- packages/fuel-gauge/src/contract-factory.test.ts
- packages/fuel-gauge/src/transaction-summary.test.ts
- packages/providers/package.json
- packages/providers/src/transaction-summary/assemble-transaction-summary.ts
- packages/providers/src/transaction-summary/date.test.ts
- packages/providers/src/transaction-summary/date.ts
- packages/providers/src/transaction-summary/index.ts
- packages/providers/src/transaction-summary/types.ts
- packages/providers/test/fixtures/transaction-summary.ts
- pnpm-lock.yaml
This PR adds the property `date` to the `TransactionSummary`.
> request from @LuizAsFight
> feat: add `date` to `TransactionSummary`

- .changeset/spicy-tables-taste.md
- apps/docs-snippets/src/guide/scripts/script-custom-transaction.test.ts
- internal/check-imports/src/references.ts
- packages/fuel-gauge/src/transaction-summary.test.ts
- packages/program/src/functions/base-invocation-scope.ts
- packages/providers/src/transaction-request/transaction-request.ts
- packages/providers/src/transaction-response/transaction-response.ts
- packages/providers/src/transaction-summary/assemble-transaction-summary.ts
- packages/providers/src/transaction-summary/get-transaction-summary.ts
- packages/providers/src/utils/fee.ts
- packages/script/src/script.test.ts
- packages/transactions/src/configs.ts
- packages/wallet/src/account.ts
> refactor: Purging `GAS_PRICE_FACTOR` and `GAS_PER_BYTE` constants

- .changeset/wet-chefs-wave.md
- packages/providers/src/provider.ts
- packages/providers/test/provider.test.ts
> fix: make `nodeInfoCache` and `chainInfoCache` private (`Provider`)

- .changeset/forty-items-cross.md
- packages/fuel-gauge/src/contract.test.ts
- packages/wallet/src/utils.test.ts
- packages/wallet/src/utils.ts
- Close: https://github.com/FuelLabs/fuels-ts/issues/1393
> fix: `transferToContract` for amounts higher than u16

- .changeset/gentle-adults-notice.md
- packages/fuels/src/cli/commands/dev/startFuelCore.test.ts
- packages/fuels/src/cli/commands/dev/startFuelCore.ts
> fix: fuel core graceful shutdown

- .changeset/stale-jokes-clap.md
- packages/create-fuels/src/cli.ts
- templates/nextjs/src/pages/index.tsx
Some minor adjustments to the links in scaffolding CLI's logs and template, as requested by the devrel team after a brief review.
> chore: update and add docs links in scaffolding CLI

- .changeset/angry-balloons-cover.md
- .changeset/brown-zebras-remember.md
- .changeset/clean-fans-wait.md
- .changeset/cold-worms-heal.md
- .changeset/curly-poems-glow.md
- .changeset/long-ways-rule.md
- .changeset/moody-walls-admire.md
- .changeset/nice-flowers-invent.md
- .changeset/orange-mangos-yell.md
- .changeset/pretty-goats-matter.md
- .changeset/six-shoes-impress.md
- .changeset/six-singers-sit.md
- .changeset/sour-apples-prove.md
- .changeset/stale-flowers-cheer.md
- .changeset/stale-jokes-clap.md
- .changeset/swift-dancers-cheat.md
- .changeset/violet-mice-rest.md
- .changeset/wicked-pens-mix.md
- packages/fuel-core/lib/install.js
- Simple fix for triggering a new release
- Re-adding lost changesets from https://github.com/FuelLabs/fuels-ts/commit/d0d79515198d7f0717c9f7d3fa1ef71806ef8cb0
- _The first release attempt [failed](https://github.com/FuelLabs/fuels-ts/actions/runs/7449110901/job/20273702114) and everything was lost_
> chore: removing unnecessary await

- packages/providers/src/operations.graphql
- packages/providers/src/provider.ts
- packages/providers/src/transaction-response/transaction-response.ts
- packages/providers/src/transaction-summary/receipt.ts
- packages/providers/src/utils/receipts.ts
- packages/providers/test/fixtures/receipts.ts
A couple of revisions on top of:
- https://github.com/FuelLabs/fuels-ts/pull/1710
> chore: adjusting types and reducing castings

- .changeset/cyan-mice-suffer.md
- .github/workflows/pr-release.yaml
- apps/demo-react-cra/src/App.tsx
- packages/math/src/bn.ts
> fix: resolve transpilation issue with `BN`

- .github/workflows/test.yaml
Got commented out in #1908 to fix `master`.
> fix: uncomment coverage code

- .github/workflows/breaking-change-pr-release.yaml
Dispatch an action to open a PR on wallet repo.
| 📷  |
| ---- |
| <img width="645" alt="Screenshot 2024-03-21 at 09 25 12" src="https://github.com/FuelLabs/fuels-ts/assets/7074983/eaaceb33-3307-46b5-b3fe-b44bfe369cdd"> |
> ci: update wallet

- .github/workflows/breaking-change-pr-release.yaml
- Close: https://github.com/FuelLabs/fuels-ts/issues/1929
> chore: fix breaking change PR release workflow

- .changeset/tough-parrots-occur.md
This PR is to fix the changeset from `patch` to `minor` as it's a breaking change.
> feat!: improve signing DX

- .github/workflows/pr-lint.yaml
- .github/workflows/release.yaml
- package.json
- pnpm-lock.yaml
- scripts/changeset/changeset-publish.ts
- scripts/changeset/get-latest-release.mts
- scripts/changeset/update-changelog.mts
This PR fixes issues found after the merge of #1849.
closes #1937
> fix: patching old releases

- .changeset/slow-mails-sit.md
- packages/account/src/providers/memory-cache.test.ts
This PR is intended to fix these annoying flaky tests:
https://github.com/FuelLabs/fuels-ts/actions/runs/8711150584/job/23894625257?pr=2037#step:10:512
> fix: `MemoryCache` flaky tests 

- .changeset/kind-roses-trade.md
- .github/workflows/test.yaml
- Close: https://github.com/FuelLabs/fuels-ts/issues/2196
> chore: fix CI e2e test

- .changeset/clever-years-invent.md
- packages/account/README.md
> docs: updated inconsistent `@fuel-ts/account` README

- .changeset/rude-ants-thank.md
- apps/docs/src/guide/fuels-cli/commands.md
> docs: add notice about `forc deploy` in `fuels deploy` docs

- .changeset/neat-ladybugs-matter.md
- .fuel-core/configs/stateConfig.json
- apps/docs-snippets/src/guide/transactions/transaction-request.test.ts
- packages/account/src/account.test.ts
- packages/account/src/providers/transaction-request/transaction-request.test.ts
- packages/account/src/providers/transaction-request/transaction-request.ts
- packages/account/src/providers/utils/gas.ts
- packages/fuel-gauge/src/policies.test.ts
- packages/program/src/functions/base-invocation-scope.ts
- Close: https://github.com/FuelLabs/fuels-ts/issues/2201
> fix: handling optional policies

- .github/workflows/release.yaml
Fixes [this](https://github.com/FuelLabs/fuels-ts/actions/runs/9033118035/job/24822712898#step:20:21).
> fix: typo in update nightly docs workflow

- .changeset/big-ducks-act.md
- packages/utils/src/utils/arrayify.test.ts
- packages/utils/src/utils/arrayify.ts
> feat: improve `arrayify` error message

- .changeset/nervous-turtles-bow.md
- .github/workflows/test.yaml
- .textlintrc.json
- CONTRIBUTING.md
- apps/create-fuels-counter-guide/src/lib.ts
- apps/docs-snippets/src/guide/wallets/instantiating-wallets.test.ts
- apps/docs/src/guide/cookbook/graphql-integration.md
- apps/docs/src/guide/cookbook/wallet-sdk-and-react-hooks.md
- apps/docs/src/guide/creating-a-fuel-dapp/deploying-a-dapp-to-testnet.md
- apps/docs/src/guide/getting-started/connecting-to-testnet.md
- apps/docs/src/guide/getting-started/usage.md
- packages/account/src/configs.test.ts
- packages/account/src/configs.ts
- packages/account/test/fuel-wallet-connector.test.ts
- packages/fuel-gauge/src/e2e-script.test.ts
- templates/nextjs/src/lib.ts
> fix: update testnet URL

- scripts/changeset/get-full-changelog.mts
> chore: adding missing comma

- packages/create-fuels/src/bin.ts
- packages/create-fuels/src/cli.ts
- packages/create-fuels/src/lib/rewriteTemplateFiles.test.ts
- packages/create-fuels/test/cli.test.ts
- packages/create-fuels/test/utils/bootstrapProject.ts
- scripts/tests-find.sh
- Stabilise testing for `create fuels` templating
> chore: stabilise testing for create fuels templating

- .changeset/tender-birds-tap.md
- Fix incorrect changeset from:
https://github.com/FuelLabs/fuels-ts/pull/2777
> chore: fix changeset

- .github/actions/test-setup/action.yaml
- .github/workflows/pr-release.yaml
- .github/workflows/release.yaml
- package.json
Revised build split and made the faster default.
Ignores packages named: `docs*`, `demo-*`, `template-*`.
```console
pnpm build
```
```
Tasks:    25 successful, 25 total
Cached:    0 cached, 25 total
Time:    24.423s
```
Everything.
```console
pnpm build:all
```
```
Tasks:    29 successful, 29 total
Cached:    0 cached, 29 total
Time:    49.914s
```
> chore: revising build scripts

- .github/actions/test-setup/action.yaml
- .github/workflows/pr-release.yaml
- .github/workflows/release.yaml
- package.json
Reverts the following:
- #2909 
- #2918
> chore: revert build script changes

- .changeset/new-numbers-talk.md
- packages/account/src/test-utils/launchNode.ts
Quick and temporary workaround until https://github.com/FuelLabs/fuel-core/issues/2107 is fixed.
This fixes test flakiness around [this](https://github.com/FuelLabs/fuels-ts/issues/2967#issuecomment-2294412606).
> fix: gas price estimation test flakiness

- .changeset/eleven-ties-bathe.md
- .github/workflows/pr-validate-changesets.yaml
> fix: PRs tagged as breaking must have minor changes

- .changeset/wet-hairs-beg.md
- packages/account/src/test-utils/launchNode.test.ts
I've seen this way too many times. ([ref](https://github.com/FuelLabs/fuels-ts/issues/2967#issuecomment-2313138412))
> chore: increase test timeout to reduce flakiness

- .changeset/pink-apricots-sell.md
- packages/account/src/test-utils/launchNode.test.ts
- packages/fuel-gauge/src/contract-factory.test.ts
- Closes #3109
Increasing timeout for heavy tests in an attempt to resolve flakiness.
> chore: fixing flaky tests

- .changeset/wild-bulldogs-cheer.md
- packages/fuel-gauge/src/transaction-upgrade.test.ts
- Closes #3150
- Closes TS-646
> chore: increase timeout for upgrade/upload tx types test

- templates/vite/src/App.tsx
- templates/vite/src/components/Faucet.tsx
- templates/vite/src/components/LocalFaucet.tsx
- templates/vite/src/components/Wallet.tsx
- templates/vite/src/hooks/useProvider.ts
- Adds routing via query parameters
- Adds an embedded faucet
> feat: add faucet page and query params integration

- packages/abi/src/matchers/sway-type-matchers.ts
- Applying the same changes as https://github.com/FuelLabs/fuels-ts/pull/3162
> chore: added start of line to ABI regex matchers

- .changeset/breezy-drinks-reply.md
- packages/create-fuels/package.json
- pnpm-lock.yaml
- Downgrade ora from `8.1.0` to `5.4.1`
> chore: downgrade ora from `8.1.0` to `5.4.1`

- .github/dependabot.yml
- This PR will separate minor and major versions for dependabot upgrades.
> chore: separate minor and major versions

- .changeset/serious-carrots-nail.md
- apps/docs-snippets/src/guide/utilities/using-assets.test.ts
- apps/docs/.vitepress/config.ts
- apps/docs/spell-check-custom-words.txt
- apps/docs/src/guide/utilities/using-assets.md
> Closes TS-658
- Closes #3188
- Added documentation for using assets
> docs: added assets guide

- packages/contract/src/contract-factory.ts
- packages/fuels/src/cli/commands/deploy/deployPredicates.ts
- packages/fuels/src/cli/commands/deploy/index.ts
- packages/fuels/src/cli/commands/deploy/savePredicateFiles.ts
- packages/fuels/src/cli/commands/deploy/saveScriptFiles.ts
- packages/fuels/src/cli/config/forcUtils.ts
- packages/fuels/src/cli/types.ts
> add pseudocode for predicates deploy and file saves

- .changeset/unlucky-laws-add.md
- packages/account/src/providers/operations.graphql
- Optimize the `getBlockWithTransactions` query
> chore: optimize blockWithTransactions query

- .changeset/four-chicken-think.md
- .github/workflows/pr-release.yaml
- packages/account/src/connectors/fuel.ts
- Fixed the listener setup for the current connector
> fix: setup listeners current connector

- .changeset/unlucky-buses-cheer.md
- packages/account/src/account.test.ts
- packages/account/src/account.ts
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
> chore: validate tx max number of inputs

- apps/docs/src/guide/contracts/contract-balance.md
- apps/docs/src/guide/contracts/cost-estimation.md
- apps/docs/src/guide/contracts/dependency-estimation.md
- apps/docs/src/guide/contracts/deploying-contracts.md
- apps/docs/src/guide/contracts/minted-token-asset-id.md
- apps/docs/src/guide/predicates/methods.md
- apps/docs/src/guide/provider/provider-options.md
- apps/docs/src/guide/testing/launching-a-test-node.md
- apps/docs/src/guide/utilities/using-assets.md
- apps/docs/src/guide/wallets/checking-balances.md
- apps/docs/src/guide/wallets/connectors.md
- Fixing `docs-api` links ([ref](https://github.com/FuelLabs/fuels-ts/actions/runs/12211447783/job/34068730507))
> docs: fix api links

- apps/docs-api/index.md
- apps/docs/src/guide/contracts/managing-deployed-contracts.md
- apps/docs/src/guide/contracts/minted-token-asset-id.md
Follow up to:
- #3492 
- Fixing the broken lint [step](https://github.com/FuelLabs/fuels-ts/actions/runs/12657412177/job/35272099416?pr=3521).
> docs: updated references of interfaces

- .github/workflows/linear-pr-integration.yaml
- .github/workflows/pr-validate-changesets.yaml
- .github/workflows/release.yaml
- Part of #3603
- Updated all PAT token usage (`REPO_TOKEN`) for the `GITHUB_TOKEN`
> chore: remove GitHub PAT token usage

- apps/docs/src/guide/contracts/proxy-contracts.md
> docs: text nits

- .changeset/kind-ants-scream.md
- apps/docs/src/guide/getting-started/running-a-local-fuel-node.md
- link-check.config.json
- Update documentation for running a local Fuel node
- Removed lint links for now present docs
> docs: update local Fuel node docs

- .changeset/breezy-mugs-cheat.md
- packages/fuel-gauge/src/network.test.ts
> test: fix predicate test in network test suite

- .changeset/dull-feet-beg.md
- packages/account/src/mnemonic/mnemonic.test.ts
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- packages/account/src/providers/resource-cache.test.ts
- packages/account/src/providers/transaction-response/getDecodedLogs.ts
- packages/account/src/providers/utils/extract-tx-error.ts
- packages/address/src/address.ts
- packages/fuel-gauge/src/advanced-logging.test.ts
- packages/fuel-gauge/src/contract.test.ts
- packages/fuel-gauge/src/dry-run-multiple-txs.test.ts
- packages/fuel-gauge/src/edge-cases.test.ts
- packages/fuel-gauge/src/funding-transaction.test.ts
- packages/fuel-gauge/src/predicate-conditional-inputs.test.ts
- packages/fuel-gauge/src/token-test-contract.test.ts
- packages/fuel-gauge/src/transaction-response.test.ts
Fixing some typos within the code base and test suites
> chore: fixing code typos

- .changeset/unlucky-trainers-clap.md
- apps/docs/src/guide/wallets/mnemonic-wallet.md
- apps/docs/src/guide/wallets/snippets/mnemonic/from-mnemonic-phrases-1.ts
- apps/docs/src/guide/wallets/snippets/mnemonic/from-mnemonic-phrases-2.ts
- packages/account/src/account.test.ts
- packages/account/src/providers/message.ts
- packages/account/src/wallet-manager/wallet-manager.test.ts
- packages/fuel-gauge/src/coverage-contract.test.ts
> docs: fix wallet docs snippet

- .changeset/hip-peas-run.md
- .github/workflows/changesets-pr.yaml
- .github/workflows/release.yaml
- Relates to: #3603 
- Adds the repositories to the app token request.
> chore: use repositories for app token

- .changeset/eight-dots-collect.md
- .github/dependabot.yml
- apps/create-fuels-counter-guide/package.json
- apps/demo-react-vite/package.json
- package.json
- packages/abi-typegen/package.json
- packages/create-fuels/package.json
- packages/fuels/package.json
- pnpm-lock.yaml
- templates/vite/package.json
- Upgraded the following packages
| Package | From | To |
| --- | --- | --- |
| [eslint-config-airbnb-typescript](https://github.com/iamturns/eslint-config-airbnb-typescript) | `17.1.0` | `18.0.0` |
| [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) | `9.1.0` | `10.0.1` |
| [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc) | `46.8.2` | `50.6.3` |
| [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/HEAD/packages/eslint-plugin-react-hooks) | `4.6.2` | `5.1.0` |
| [commander](https://github.com/tj/commander.js) | `12.1.0` | `13.1.0` |
- Added follow-up issues and added ignore notices to the `dependabot.yml` file:
| Package | Issues | 
| --- | --- | 
| eslint + plugins | #3724 |
| [tsup](https://github.com/egoist/tsup) | #2666  | …
> chore: upgraded various dependencies

- .changeset/dirty-eyes-ring.md
- .changeset/silent-points-punch.md
- packages/account/src/providers/fuel-graphql-subscriber.ts
- packages/account/src/providers/provider.test.ts
Reverts #3695 as it was not found to actually fix the underlying issue.
> chore: revert "fix: ignored subscriptions not being read"

- .changeset/dry-rivers-repeat.md
- packages/fuel-gauge/src/network.test.ts
> test: add withdraw to base layer test in network suite

- .github/workflows/changesets-pr.yaml
- .github/workflows/release.yaml
Rolling back previous workflow environment settings.
> ci(release): fix release v0.100.0

- .changeset/famous-donuts-guess.md
- .github/workflows/publish-to-next.yaml
Fix for the temp release message from #3792, [incorrectly copied](https://github.com/FuelLabs/fuels-ts/pull/3792/commits/b5d34ef706b657f3e81abc20b3c76521300f6754) from a PR suggestion.
> chore: fix pr release message

- .changeset/curvy-humans-drum.md
- apps/docs/.eslintrc.cjs
- apps/docs/scripts/test-template.ts
- apps/docs/scripts/wrap-snippets.ts
- apps/docs/src/guide/cookbook/snippets/resubmitting-failed-transactions/wrong-resubmission.ts
- apps/docs/src/guide/provider/snippets/functionality/get-message-proof-block-id.ts
This PR fixes the [these 2 flaky tests](https://github.com/FuelLabs/fuels-ts/actions/runs/13933366078/job/38995741313?pr=3747#step:7:2023)
> chore: fix flaky tests

- .changeset/crazy-tools-run.md
- .github/dependabot.yml
- internal/tsup/src/index.ts
- package.json
- packages/account/src/providers/utils/json.ts
- pnpm-lock.yaml
- Closes #2666
Upgraded `tsup` to `8.3.5`
> chore: upgraded `tsup` to `8.3.5`

- .changeset/brown-things-behave.md
- apps/create-fuels-counter-guide/package.json
- package.json
- packages/utils/package.json
- pnpm-lock.yaml
- templates/nextjs/package.json
- templates/vite/package.json
- vitest.shared.config.mts
> chore: upgrade vitest to `3.0.9`

- .github/CODEOWNERS
> chore: updating code owners

- .changeset/silent-areas-sink.md
- .github/workflows/publish-to-next.yaml
Pretty much what the title says.
> chore: prevent temporary PR message from spamming PR's feed

- .changeset/green-parts-decide.md
- packages/account/src/providers/operations.graphql
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- packages/account/src/providers/utils/serialization.ts
- packages/account/test/fixtures/nodeInfo.ts
- packages/errors/src/error-codes.ts
- Closes #3823
- Adjusted feature detection for balances indexation
> fix: adjust feature detection for balances

- .changeset/slow-squids-travel.md
- apps/create-fuels-counter-guide/src/lib.tsx
- apps/create-fuels-counter-guide/src/main.tsx
- templates/nextjs/src/app/layout.tsx
- templates/nextjs/src/lib.tsx
- templates/vite/src/lib.tsx
- templates/vite/src/main.tsx
Fixed the templates by passing through the `chainId` to the react `FuelProvider`
> fix: connector detection of correct chain

- .changeset/upset-bears-change.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- Closes #3842
- Fixed issue with silent request failures for fetching the chain while instantiating providers
> fix: silent chain fetch request failures

- apps/docs/src/guide/getting-started/connecting-to-the-network.md
Swapping incorrect RPC URLs between Mainnet and Testnet.
> docs: swapping RPC urls

- .changeset/free-impalas-beam.md
- apps/demo-nextjs/package.json
- apps/demo-react-cra/package.json
- apps/demo-react-vite/package.json
- packages/account/package.json
- packages/contract/package.json
- packages/program/package.json
- packages/transactions/src/configs.ts
- pnpm-lock.yaml
> chore: upgrading `@fuels/vm-asm` package

- .changeset/light-moose-visit.md
- package.json
- packages/account/src/providers/provider.ts
- packages/account/src/providers/utils/serialization.test.ts
- packages/account/src/test-utils/setup-test-provider-and-wallets.ts
- packages/fuel-gauge/src/transaction.test.ts
- Closes #3820
Fixed provider async methods and tests.
> fix: provider async methods and tests

- .changeset/spotty-streets-lie.md
- packages/account/src/providers/transaction-response/transaction-response.ts
- packages/account/test/fuel-wallet-connector.test.ts
> chore: renaming method for consistency

- .changeset/khaki-zoos-cough.md
- packages/account/src/providers/operations.graphql
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- packages/account/src/providers/utils/serialization.ts
- packages/account/test/fixtures/chain.ts
- Closes #3810
- Fixed `Provider` auto-refetch
> fix: provider auto-refetch

- .changeset/eighty-lies-end.md
- packages/fuels/src/setup-launch-node-server.ts
- vitest.browser.config.mts
> chore: fix flaky Vitest tests in browser environment

- .changeset/curvy-coats-laugh.md
- apps/docs/src/guide/predicates/methods.md
- apps/docs/src/guide/predicates/snippets/methods/modified-data.ts
- apps/docs/src/guide/predicates/snippets/methods/no-modified-data.ts
- apps/docs/src/guide/predicates/snippets/methods/set-predicate-new-data.ts
- packages/account/src/predicate/predicate.ts
- packages/fuel-gauge/src/predicate/predicate-arguments.test.ts
- Closes #3818
- Added method `setData` to `Predicate` class
> feat: add `Predicate` method `setData`

- .changeset/wild-dryers-retire.md
- apps/docs/src/guide/cookbook/combining-utxos.md
- packages/account/src/account.ts
- packages/account/src/consolidate-coins.test.ts
- Closes #3855 
- Added method for consolidating non-base assets.
> feat: consolidate non-base asset
