FuelLabs/fuels-ts

- .vscode/extensions.json
- .vscode/settings.json
Improve DX on **vscode**, by recommending `prettier` and `eslint` extensions and also enforcing format right after save, avoiding lint issues on commit time.
- Add two extensions to the `vscode/extensions.json` recommendations:
- [esbenp.prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode);
- [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).
- Add `settings.json` to make default `auto` format and lint after save.
> VSCODE: add auto format/lint

- packages/wallet/package.json
- packages/wallet/src/hasher.ts
- Set to zero on `hashTransaction` the defined `outputs`.
- Add `lodash.deepClone` to remove reference from `transactionRequest` param.
> feat: zero out output fields on hashTransaction

- packages/testcases/src/sendTransaction.json
- packages/wallet/src/wallet.test.ts
- packages/wallet/src/wallet.ts
- Add `sendTransaction` on Wallet;
- Add `Provider` instance on Wallet;
- Add simple provider configuration on Wallet by enabling URL as a valid provider param;
- Add `senTransaction.json` object on `@fuel-ts/testcases`;
- Zero out `witnessesCount` before hashing/signing transaction;
- Populate signature on  `sendTransaction`.
- On `witnessesCount` should be zeroed?
- `ZERO_B256` and `genBytes32`  could be used across packages. Maybe create a package `@fuel-ts/helpers`?
- `FUEL_NETWORK_URL` could be injected using `.env` or another strategy across packages.
> feat: add sendTransaction

- packages/wallet/src/types/GenerateOptions.ts
- packages/wallet/src/wallet.ts
- Enable to pass provider config on `Wallet.generate(options)`.
> Provider configuration on `Wallet.generate`

- README.md
- Change link from point to readme folder to docs pages.
> chore: change docs link to point to docs page

- packages/contract/src/test-contract/Forc.toml
- packages/contract/src/test-contract/lib-core/Forc.toml
- packages/contract/src/test-contract/lib-std/Forc.toml
- packages/example-contract/Forc.toml
- packages/example-contract/lib-core/Forc.toml
- packages/example-contract/lib-std/Forc.toml
- packages/providers/src/test-contract/Forc.toml
- packages/providers/src/test-contract/lib-core/Forc.toml
- packages/providers/src/test-contract/lib-std/Forc.toml
Updating 'Forc.toml' files to use `authors` instead of `author`. This enables compatibility with the change being made in this PR https://github.com/FuelLabs/sway/pull/822
> change author to authors in Forc.toml files

- .github/workflows/sematic-release.yaml
- .releaserc.json
realized this is easier to `--dry-runs`  and semantic-release + mono repos are bad for my OCD
> chore: Update releaserc and allow dry-runs on ci

- .releaserc.json
- package-lock.json
- package.json
99% sure the token is valid, but we're getting `EINVALIDNPMTOKEN`
This seems to be the recommending fix
> When releasing a monorepos you may get EINVALIDNPMTOKEN error. The more packages, the more chance of error, unfortunately.
https://github.com/dhoulb/multi-semantic-release#npm-invalid-npm-token
> fix: Throttle npm whoami

- package.json
- packages/abi-coder/src/coder.test.ts
- packages/abi-coder/src/coders/b256.ts
- packages/hdwallet/tsconfig.json
- packages/wallet/tsconfig.json
Turns out the previous "B256 with all zero bytes" issue we fixed was actually a "B256 with leading zero bytes" issue.
With this PR, the bug is fixed and encoder only accepts exactly 32 bytes. So `0x0`, `0x00` and such are invalid now which should be safer.
> Fix encoding of B256s with leading zero bytes

- package-lock.json
- packages/providers/package.json
- When installing the packages from npm, it runs `post/pre install` scripts. It's preferable to use ' prepare' for scripts that should run only on development env.
> fix: change postinstall to prepare

- packages/abi-coder/src/abi-coder.ts
- packages/abi-coder/src/coder.test.ts
Added a skip directly on the contract code, but left it out on the ABI coder.
This PR skips the `()` type aka empty on strict match.  The reason why we don't have a parser for this is that we're using the abi parser from ethers and params are interpreted as a tuple.
> fix: abi skip empty

- packages/typechain-target-fuels/src/parser/abiParser.test.ts
- packages/typechain-target-fuels/src/parser/abiParser.ts
- When the contract has the declaration with empty param `()`. It creates a type declaration without the last param, which is not required.
Declaration;
```
fn deposit(gas_: u64, amount_: u64, asset_id_: b256, params: ()) {
```
Result;
```ts
encodeFunctionData(
functionFragment: "deposit",
values: [BigNumberish, BigNumberish, string]
): string;
```
> fix: remove empty params from types

- packages/contract/src/contract.ts
- packages/contract/src/storage-test-contract.test.ts
This PR:
- Renames the internal `buildCall`, which was intended to just do dry runs but was actually submitting transactions, to `buildSubmit`. (`buildSubmit` is used for building `contract.functions.xyz` methods.)
- Introduces `buildCall` that actually does dry runs and uses that to build `contract.callStatic.xyz` methods.
So basically:
```ts
// Submits a tx
await contract.functions.initialize_counter(1337);
// Does not submit a tx
const count = await contract.callStatic.counter();
```
> feat: add `callStatic` methods to Contract

- package-lock.json
- packages/example-contract/src/example-contract.test.ts
- packages/fuels/package.json
- packages/fuels/src/index.ts
- packages/typechain-target-fuels/example/types/Demo.d.ts
- packages/typechain-target-fuels/example/types/Token.d.ts
- packages/typechain-target-fuels/example/types/factories/Demo__factory.ts
- packages/typechain-target-fuels/example/types/factories/Token__factory.ts
- packages/typechain-target-fuels/src/codegen/index.ts
- Change imports removing ether and specific ones like `@fuels-ts/contract`
- Add a test on `example-contract` to use the ContractFactory directly.
- Add `@ethersproject/bytes` on `fuels` in this way. It's possible to use `BytesLike` and others on projects without installing other packages.
Before the imports on generated files
```
import { Interface, FunctionFragment, DecodedValue } from "@fuel-ts/abi-coder";
import { Contract, Overrides } from "@fuel-ts/contract";
import { Provider } from "@fuel-ts/providers";
import { BigNumberish } from "@ethersproject/bignumber";
import { BytesLike } from "@ethersproject/bytes";
```
Now
```
import type {
Interface,
FunctionFragment,
DecodedValue,
Contract,
Overrides,
BigNumberish,
BytesLike,
} from "fuels";
```
closes: #183
> feat: change `typechain` imports to fuels

- package-lock.json
- packages/signer/src/signer.test.ts
- packages/signer/src/signer.ts
- packages/wallet/package.json
- packages/wallet/src/wallet-spec.ts
- packages/wallet/src/wallet.test.ts
- packages/wallet/src/wallet.ts
- packages/wallet/tsconfig.json
- Add `fromSeed, fromMnemonic, fromExtendedKey` methods to Wallet. The designed solution didn't keep seed, mnemonic phrase, or other related info on the wallet instance, removing possible leaking of it on the wallet level. Because of that `derivePath and deriveIndex` methods can't be implemented on the wallet level. At this time the idea is to bring a new High Order Component something like `Wallet Manager`.
- Add `extendPublicKey` on `@fuels-ts/signer`, converting a compact publicKey to an extended publicKey.
- Add the `connect` method to `@fuels-ts/wallet`, connect to a different provider without the need to recreate the wallet.
closes: #146
> feat: add hdwallet and mnemonic features to wallet

- packages/abi-coder/src/abi-coder.ts
- packages/abi-coder/src/coder.test.ts
- packages/abi-coder/src/coders/abstract-coder.ts
- packages/abi-coder/src/coders/array.ts
- packages/abi-coder/src/coders/b256.ts
- packages/abi-coder/src/coders/number.ts
- packages/abi-coder/src/coders/string.ts
- packages/abi-coder/src/coders/tuple.ts
- packages/abi-coder/src/fragments/fragment.ts
- packages/abi-coder/src/interface.test.ts
- packages/abi-coder/src/interface.ts
- packages/contract/src/call-test-contract/call-test-contract.test.ts
- packages/typechain-target-fuels/src/parser/parseSvmTypes.test.ts
- packages/typechain-target-fuels/src/parser/parseSvmTypes.ts
Migrate to use the new array format.
One thing I noticed is that the ABI coder allowed strings and all the tests were testing this.  Currently, we only allow JSON ABI formats.  I update all the tests and refactored the code to do this.
> fix!: Update to use new ABI format and only allow json framgents

- packages/abi-coder/src/abi-coder.ts
- packages/abi-coder/src/fragments/fragment.ts
- When declaring a JSONFrament `input/outputs` name is not required.
This works;
```ts
const contract = await setup([
{
type: 'function',
name: 'return_context_asset',
outputs: [
{
name: 'arg0',
type: 'b256',
},
],
},
]);
```
This should work also;
```ts
const contract = await setup([
{
type: 'function',
name: 'return_context_asset',
outputs: [
{
type: 'b256',
},
],
},
]);
```
> fix: set json fragment name optional

- packages/abi-coder/src/abi-coder.ts
- packages/abi-coder/src/fragments/fragment.ts
- packages/typechain-target-fuels/example/demo.json
- packages/typechain-target-fuels/example/token.json
- packages/typechain-target-fuels/example/types/Demo.d.ts
- packages/typechain-target-fuels/example/types/Token.d.ts
- packages/typechain-target-fuels/example/types/factories/Demo__factory.ts
- packages/typechain-target-fuels/example/types/factories/Token__factory.ts
- packages/typechain-target-fuels/src/codegen/functions.ts
- packages/typechain-target-fuels/src/codegen/index.ts
- packages/typechain-target-fuels/src/codegen/types.test.ts
- packages/typechain-target-fuels/src/codegen/types.ts
- packages/typechain-target-fuels/src/parser/abiParser.ts
- Add support to typed return on contract methods from generated code.
Before:
```
return_struct(
arg0: BigNumberish,
overrides?: Overrides & { from?: string | Promise<string> }
): Promise<any>;
```
With generated types:
```
type Ret0Struct = { sender: string; receiver: string; Ret1: Ret1Struct };
return_struct(
arg0: BigNumberish,
overrides?: Overrides & { from?: string | Promise<string> }
): Promise<Ret0Struct>;
```
closes: #179
> feat: add types on contract factory generated code

- packages/abi-coder/src/abi-coder.ts
- packages/typechain-target-fuels/src/codegen/structs.ts
- packages/typechain-target-fuels/src/codegen/types.test.ts
- packages/typechain-target-fuels/src/codegen/types.ts
- packages/typechain-target-fuels/src/common.ts
- packages/typechain-target-fuels/src/parser/abiParser.test.ts
- packages/typechain-target-fuels/src/parser/abiParser.ts
- packages/typechain-target-fuels/src/parser/parseSvmTypes.test.ts
- packages/typechain-target-fuels/src/parser/parseSvmTypes.ts
- Add support to custom types like `struct` and `enum` on the `typechain`.
- Add support to struct and enum on `ABI Coder`
Contract ABI
```rust
fn foo(address_id: Address, asset_id: ContractId) -> Address;
fn bar(sum_params: MySumType) -> MySumType;
```
Without custom struct;
```ts
foo(
address_id: any,
asset_id: any,
overrides?: Overrides & { from?: string | Promise<string> }
): Promise<any>;
bar(
sum_params: any,
overrides?: Overrides & { from?: string | Promise<string> }
): Promise<any>;
```
With custom struct;
```ts
export type ContractIdStruct = { value: string };
export type AddressStruct = { value: string };
export type MySumTypeStruct = { x: BigNumberish; y: BigNumberish };
foo(
address_id: AddressStruct,
asset_id: ContractIdStruct,
overrides?: Overrides & { from?: string | …
```
> Add support to ABI types `struct` and `enum`

- packages/abi-coder/src/abi-coder.ts
- packages/abi-coder/src/coder.test.ts
- packages/abi-coder/src/coders/tuple.ts
Encoding/Decoding  tuples from the ABI
e.g.
```
{
name: 'input',
type: '(u64, u64)',
components: null,
},
```
> feat: support abi fuel types

- packages/contract/src/call-test-contract/call-test-contract.test.ts
- packages/contract/src/contract.ts
When calling a contract sometimes we need to change the request, add inputs/outputs, or other things. To make easier to access it before submitting/calling a contract we add a `tranformRequest`. This follow API implementations commons on other request libs like Axios.
```ts
await contract.functions.return_context_asset({
amount: 0,
assetId: '0x000...000',
transformRequest: (request: ScriptTransactionRequest) => {
request.inputs = [];
request.outputs = [];
return request;
},
});
```
> feat: adds transformRequest method on contract call

- packages/contract/src/call-test-contract/call-test-contract.test.ts
- packages/contract/src/contract.ts
This PR replaces the current way of forwarding coins to a contract call from the `amount`/`assetId` override combo to a single `forward` property.
Another change is that when you call a contract using `forward`, the SDK will automatically get coins from the wallet so:
- You don't have to call `getCoinsToSpend` and manually insert coins.
- Both this new functionality and the current txn funding mechanism uses a single `getCoinsToSpend` call so https://github.com/FuelLabs/fuels-ts/issues/229 is fixed as a side effect.
```ts
// Before
await contract.functions.<method>({
assetId: '0x0000....0000',
amount: 1_000_000,
transformRequest: async (request) => {
// Remove all previous inputs with the same coin
request.inputs = request.inputs.filter(i => {
return !(i.type === InputType.Coin && …
```
> feat: replace `amount`/`assetId` overrides with `forward`

- docker-compose.yml
- packages/providers/src/provider.test.ts
- packages/wallet/src/transfer.test.ts
- packages/wallet/src/wallet.ts
- services/fuel-core/Dockerfile
A smooth upgrade besides the "duplicate UTXO" error I got on a transfer test. Reducing `coinsToSpend` calls to one solved the issue.
> feat!: upgrade to fuel-core 0.6.3

- README.md
- package.json
- packages/abi-coder/package.json
- packages/constants/package.json
- packages/contract/package.json
- packages/fuels/package.json
- packages/hasher/package.json
- packages/hdwallet/package.json
- packages/interfaces/package.json
- packages/keystore/package.json
- packages/merkle-shared/package.json
- packages/merkle/package.json
- packages/merklesum/package.json
- packages/mnemonic/package.json
- packages/providers/package.json
- packages/signer/package.json
- packages/sparsemerkle/package.json
- packages/transactions/package.json
- packages/typechain-target-fuels/package.json
- packages/wallet-manager/package.json
- packages/wallet/package.json
- packages/wordlists/package.json
- pnpm-workspace.yaml
This pull request intends to change our environment in order to be able to use `pnpm link` correctly.
After talking with @luizstacio we tried to keep the direct import in all `package.json` by using the `publishConfig`, but we notice that if you link some package to the global pnpm store, it'll keep the same `package.json` that uses the `main` field pointing to the Typescript file. This is bad if you trying to use the linked package with some bundler (vite, react-scripts, etc) because the bundler won't handle loaders to bundle outside the package directory, and by consuming `index.ts` file this is needed.
So, we change to instead of consuming direct inside our monorepo, we need to build/watch and have all `package.json` field pointing to the same publish config. It's an annoying …
> fix: change build tasks in order to use pnpm link correctly

- scripts/release-pre.ts
Just a typo into our scripts to fix npm tag on publish ci build action
> fix: npm tag on release

- packages/contract/src/contract.ts
- packages/contract/src/scripts.ts
- packages/providers/src/index.ts
- packages/providers/src/provider.ts
- packages/providers/src/script.ts
- packages/providers/src/transaction-response/index.ts
- packages/providers/src/transaction-response/transaction-response.ts
[feat: improve TransactionResponse](https://github.com/FuelLabs/fuels-ts/pull/271/commits/782c4f3105a33935c47f24547f67aea3f26bb168)
- Extracts `TransactionResponse` from `provider.ts` into its own file.
- Adds `TransactionResponse.waitForResult()` which doesn't throw on failure so you can do your own error handling.
[feat: improve Script error handling](https://github.com/FuelLabs/fuels-ts/pull/271/commits/fb0f3c6b1ce89cbb98ad262641085875d84b7d88)
- Uses the new `waitForResult` to do better error reporting
Before:
After:
> Improve Script Error Reporting

- packages/abi-coder/src/coders/__snapshots__/coders.test.ts.snap
- packages/abi-coder/src/coders/abstract-coder.ts
- packages/abi-coder/src/coders/array.ts
- packages/abi-coder/src/coders/b256.ts
- packages/abi-coder/src/coders/boolean.ts
- packages/abi-coder/src/coders/byte.ts
- packages/abi-coder/src/coders/coders.test.ts
- packages/abi-coder/src/coders/enum.ts
- packages/abi-coder/src/coders/number.ts
- packages/abi-coder/src/coders/string.ts
- packages/abi-coder/src/coders/struct.ts
- packages/abi-coder/src/coders/tuple.ts
- packages/transactions/src/coders/byte-array.ts
- packages/transactions/src/coders/input.ts
- packages/transactions/src/coders/output.ts
- packages/transactions/src/coders/receipt.ts
- packages/transactions/src/coders/transaction.ts
- packages/transactions/src/coders/witness.ts
EnumCoder needed to left-pad its value to the max length among all possible values, but that wasn't the case.
The actual changes are in [enum.ts](https://github.com/FuelLabs/fuels-ts/pull/336/files#diff-5cc0231e0e475c5030836a1e71284195e87dafe4e2d6875a707c27d61f276647) and the rest is for length calculation.
> fix: EnumCoder not padding its value

- packages/contract/src/call-test-contract/call-test-contract.test.ts
- packages/contract/src/contract-factory.test.ts
- packages/contract/src/contract-factory.ts
- packages/contract/src/util.ts
- packages/providers/fuel-core-schema.graphql
- packages/providers/src/operations.graphql
- packages/providers/src/provider.test.ts
- packages/providers/src/provider.ts
- packages/wallet/src/transfer.test.ts
- services/fuel-core/Dockerfile
- services/fuel-core/chainConfig.json
On this PR I'm removing the ability to initialize storage slots on contract deploy [#239](https://github.com/FuelLabs/fuels-ts/pull/239).
It would be tracked by #334. The current solution stopped working due to a difference when calculating `stateRoot` between [fuel-merkle](https://github.com/FuelLabs/fuel-merkle) and [@fuel-ts/merkle](./packages/merkle).
closes: #339
> feat: update fuel-core to v0.9.2

- packages/contract/src/contract-factory.test.ts
- packages/contract/src/contract.ts
- packages/typechain-target-fuels/example/types/Demo.d.ts
- packages/typechain-target-fuels/example/types/Token.d.ts
- packages/typechain-target-fuels/src/codegen/functions.ts
- packages/typechain-target-fuels/src/codegen/index.ts
This PR makes some necessary changes for https://github.com/FuelLabs/fuels-ts/pull/288. While it was possible to write cleaner code, I thought it would be wiser to not commit to any abstractions until at least #288 and #315 land so we have a clearer path.
The idea here is to formalize the concept of a contract call in a struct called `ContractCall`, and with #288 be able to execute multiples of these in a single tx.
---
[fix: remove types for unused props](https://github.com/FuelLabs/fuels-ts/pull/348/commits/6317ff96d2e853a63343bdf9c432e0b0c97d6b07)
We actually don't put these props on Interfaces.
[feat!: make prepareCall return ContractCall](https://github.com/FuelLabs/fuels-ts/pull/348/commits/b5b5d5d1c03c755c1e3f53ef46c3a183211cd329)
Now `prepareCall` returns a new struct named …
> feat!: make prepareCall return ContractCall

- packages/providers/src/transaction-response/transaction-response.ts
This pull request intends to add `transactionId` on `TransactionResult`, mainly because we need this to show the transaction on Fuel Explorer after it's completed.
> feat: add transactionId on TransactionResult

- .vscode/launch.json
- packages/abi-coder/package.json
- packages/constants/package.json
- packages/contract/.gitignore
- packages/contract/package.json
- packages/contract/scripts/process-multicall.ts
- packages/contract/src/scripts.ts
- packages/fuels/package.json
- packages/hasher/package.json
- packages/hdwallet/package.json
- packages/interfaces/package.json
- packages/keystore/package.json
- packages/math/package.json
- packages/merkle-shared/package.json
- packages/merkle/package.json
- packages/merklesum/package.json
- packages/mnemonic/package.json
- packages/providers/package.json
- packages/script/.gitignore
- packages/script/package.json
- packages/signer/package.json
- packages/sparsemerkle/package.json
- packages/transactions/package.json
- packages/wallet-manager/package.json
- packages/wallet/package.json
- packages/wordlists/package.json
- pnpm-workspace.yaml
[chore: revert linking changes](https://github.com/FuelLabs/fuels-ts/pull/355/commits/ae2c44b9c54f8841ea3e749d0768251a74a2bc54)
Reverts some changes we did in #246 to support linking to SwaySwap when it was using Yarn. It's using PNPM too now so this shouldn't be a problem.
This fixes the VSC issue where changes in one package wasn't reflected on its dependents. You also don't have to run `build:watch` anymore, but certain things might still require you to run `pnpm build`.
I've been working with this change on my local for a week and it was a great DX improvement.
[chore: fix test launch config](https://github.com/FuelLabs/fuels-ts/pull/355/commits/cc2813804f3afa3fb5223c44ae2e7a664c59fd9e)
Fixes debugging tests using the "Testing" pane of VSC not working.
[chore: simplify contract …
> chore: various fixes and improvements

- .github/workflows/pr-lint.yaml
- .github/workflows/pr-test.yaml
- .github/workflows/publish-npm-master.yaml
- .github/workflows/test.yaml
Currently we have a single action that both runs the tests and checks the PR title. They have to share their run triggers so tests rerun when the PR title changes for example. This PR splits those into two so that doesn't happen.
This PR also stops running tests when master is merged or before publishing. We don't need this since we can "require branches to be up to date before merging which ensures pull requests have been tested with the latest code".
> chore: reorg CI config

- packages/contract/src/storage-test-contract/storage-test-contract.test.ts
#321 - This issue seems to have been already fixed in some other PR, maybe multicall one @AlicanC ?
I'm adding a test to make sure we can `dryRun` storage value of contracts using only the provider (no wallet needed).
Closes #321
> test: make sure can dryRun with only provider (no wallet)

- packages/contract/src/contract.test.ts
- packages/contract/src/contract.ts
When doing multiple forwardings the build transaction was trying to add twice the same asset resulting in an error of duplicate assets.
> fix: multi call with mutiple fowarding

- packages/contract/src/__test__/contract.test.ts
- packages/predicate/src/predicate.test.ts
- packages/predicate/src/predicate.ts
- make predicate methods accept `request` tx params
- add few tests to contract, making sure it fails when gasLimit is too low
Closes #365
> feat: make predicates functions accept request tx params

- .github/actions/ci-setup/action.yaml
- Change directory being cached
- Include `node` and `pnpm` versions in caching key.
Now `pnpm install` step is using dependencies previously cached.
Fix #409
> fix: cache pnpm dependencies

- .github/workflows/pr-lint.yaml
Ignore validate changeset when the branch name matches the ci release changeset
> ci: ignore changeset-release on pr validate

- .changeset/six-cherries-share.md
- packages/abi-coder/src/abi-coder.test.ts
- packages/abi-coder/src/abi-coder.ts
- packages/abi-coder/src/fragments/function-fragment.ts
- packages/abi-coder/src/interface.test.ts
- packages/contract/src/__test__/call-test-contract/src/main.sw
- packages/contract/src/__test__/contract.test.ts
- packages/forc-bin/package.json
Update the function fragment to  match specs and return the correct format for `enums` and `arrays`.  Some refactors were done to make sure it works with arrays with different types.
There is still an underlying issue with one of the functions; returning a single element from an array is raising an error; see below.
> feat(abi): Update interface to handle array and enum contract arguments

- .changeset/khaki-fishes-allow.md
- .changeset/wild-ants-tie.md
- .github/workflows/release.yaml
- docs/Requirements.md
Changeset has a default behavior of creating a release for each package; this is not needed, as we already use a Monorepo approach all the releases would have redundant source code. This is not only our need but also of other teams.
The approach for solving this in the meantime. Was;
- Found this PR open with the aggregate solution https://github.com/changesets/action/pull/193
- Create a Fork on https://github.com/FuelLabs/changesets-action
- Merge desire changes on `main` branch and protect the branch from changes
- Change CI to use: `FuelLabs/changesets-action@main`
The idea here is to **use our Forked version as long as needed**. As the current PR on changesets is a candidate solution but not a final solution.
> ci: create a single GitHub release/tag

- package.json
The current command `changeset publish` creates and pushes GitHub tags for each package. adding `--no-git-tag` to avoid this behavior.
> ci: no github create tags on create release

- docs/QUICKSTART.md
The import statement in App.tsx doesn't match the file name and was throwing an error.
> docs: updated import statement to match file name

- .changeset/tidy-parrots-care.md
- packages/providers/src/operations.graphql
- packages/providers/src/provider.ts
- packages/wallet/src/transfer.test.ts
- packages/wallet/src/wallet.ts
Closes out https://github.com/FuelLabs/fuels-ts/pull/226
Users can filter out utxo's from `getCoinsToSpend`
> feat: Add ExcludeId to filter out utxo_ids on coinsToSpend

- docs/QUICKSTART.md
To avoid a deprecation warning.
> docs: Update QUICKSTART.md to use `run` with `fuel-core`

- .changeset/fuzzy-pumas-fail.md
- packages/address/src/address.test.ts
- packages/address/src/address.ts
- packages/interfaces/src/index.ts
Add toJSON for parsing values to bech32 when using JSON.stringify with Address object
> feat: add toJSON to Address Class

- .changeset/short-cobras-remain.md
- packages/contract/src/contracts/functions/base-invocation-scope.ts
When using the get method on contract calls the users probably just want to read the value and not forward coins, etc. To emulate contract calls with forwarding the correct method would be `dryRun`.
> feat: change fundTransaction default to false on contract get

- .changeset/neat-singers-bathe.md
- packages/contract/scripts/build-forc-projects.sh
- packages/contract/scripts/build-multicall.sh
- packages/contract/src/__test__/call-test-contract/call-test-contract.test.ts
- packages/contract/src/__test__/contract-factory.test.ts
- packages/contract/src/__test__/contract.test.ts
- packages/contract/src/__test__/coverage-contract/coverage-contract.test.ts
- packages/contract/src/__test__/generic-types-contract/generic-types-contract.test.ts
- packages/contract/src/__test__/storage-test-contract/storage-test-contract.test.ts
- packages/contract/src/__test__/token-test-contract/token-test-contract.test.ts
- packages/example-contract/scripts/build.sh
- packages/forc-bin/package.json
- packages/predicate/scripts/build.sh
- packages/script/scripts/build-call-test-script.sh
> chore: update forc 0.24.3

- .changeset/slimy-timers-hope.md
- packages/contract/src/contracts/functions/base-invocation-scope.ts
- packages/fuel-gauge/src/contract.test.ts
The code was missing an await on the `prepareTransaction`, making it run without adding the required funds.
> fix: dryRun should fundTransaction with required coins

- .changeset/soft-elephants-drum.md
- packages/wallet-manager/src/wallet-manager.test.ts
- packages/wallet/src/wallet.test.ts
- packages/wallet/src/wallet.ts
This PR changes the sign methods to be async in this way is possible to implement Signer classes that require an async process like Wallet Extension or Hardware Wallets.
> refactor: change sign methods to be async

- .changeset/clever-donkeys-serve.md
- docs/packages/fuel-ts-contract/namespaces/internal.md
- docs/packages/fuel-ts-providers/index.md
- docs/packages/fuel-ts-providers/namespaces/internal.md
- docs/packages/fuel-ts-transactions/classes/ReceiptMessageOutCoder.md
- docs/packages/fuel-ts-transactions/enums/ReceiptType.md
- docs/packages/fuel-ts-transactions/index.md
- docs/packages/fuel-ts-wallet/namespaces/internal.md
- packages/abi-coder/src/coders/byte.ts
- packages/providers/src/transaction-response/transaction-response.ts
- packages/transactions/src/coders/receipt.test.ts
- packages/transactions/src/coders/receipt.ts
Filled in spec gap for the MessageOut receipt type
> refactor: add support for the messageout receipt type

- .changeset/poor-kiwis-attend.md
- packages/fuel-gauge/src/predicate.test.ts
- packages/fuel-gauge/src/token-test-contract.test.ts
- packages/fuel-gauge/test-projects/token_abi/src/main.sw
- packages/fuel-gauge/test-projects/token_contract/src/main.sw
- packages/providers/src/provider.ts
- packages/providers/src/util.ts
- packages/script/src/errors.ts
- packages/transactions/src/coders/receipt.ts
- packages/transactions/src/consts.ts
- packages/wallet/src/base-locked-wallet.ts
- packages/wallet/src/base-unlocked-wallet.ts
using `dryRun` or `simulate` will add output variables.
> feat: dryRun and simulate will add output variables

- .changeset/wet-phones-search.md
- packages/hasher/package.json
- packages/hasher/src/hasher.ts
- packages/keystore/src/aes-ctr-web.ts
- packages/keystore/src/keystore.ts
- pnpm-lock.yaml
When using on browser env's, Buffer is not available, requiring extra bundler configs with polyfills. Using `stringFromBuffer` from the `Keystore` package, it's possible to use Buffer on node env's and TextDecoder on browsers. Fixing the issue.
For now, we don't have a CI for automating the tests on browser #284. Because of this, I have tested it locally this are the following steps;
1. On this branch
2. Inside packages/keystore run `pnpm build` and `pnpm link --global --dir .`
3. Create an react app using `npx create-react-app my-test-app`
4. Inside the app `my-test-app` run `pnpm link --global @fuel-ts/keystore`
5. On the `src/App.js` file, paste the  following code right after `import './App.css'`;
```js
import { decrypt, encrypt } from '@fuel-ts/keystore/dist';
const data = {
'foo': …
```
> fix: remove node.js Buffer for better browser compatibility

- .changeset/lazy-beers-beam.md
- packages/abi-typegen/src/bin.ts
- packages/fuels/src/bin.ts
- packages/versions/src/bin.ts
Unlike `pnpm`,  `npm` requires binaries to have a `#!/usr/bin/env node` shebang.
This is a hotfix on top of:
- https://github.com/FuelLabs/fuels-ts/pull/661
> fix: adding node shebang to packages bin

- .changeset/long-starfishes-type.md
- packages/providers/src/transaction-request/transaction-request.ts
Simple fix for an issue I ran into when trying to manually build transactions
> fix: corrected byteslike comparison with owner

- .changeset/famous-doors-refuse.md
- packages/wallet-manager/src/wallet-manager.test.ts
- packages/wallet-manager/src/wallet-manager.ts
Working with the wallet manager, I noticed that when the unlock failed, it was not updating the state back to lock. This fix adds an error handler on `loadState` method and sets the state back to lock if it fails.
> fix: wallet manager state when unlock fails

- .changeset/lazy-trains-admire.md
- packages/contract/src/contracts/contract.ts
- packages/fuel-gauge/src/doc-examples.test.ts
> fix: make `walletOrProvider` a required param for the `Contract` constructor

- docs/QUICKSTART.md
1. Update chainConfig.json with most recent settings. The fuel-core v0.17.2 run command fails without "consensus" parameter. 
2. Update URL to forc-client repo.
3. Update contract deployment forc v0.35.2 command with correct url flag.
> fix: Update QUICKSTART.md

- .changeset/three-adults-tease.md
- packages/testcases/package.json
The package `testcaseas` still needs to be published at:
- https://www.npmjs.com/package/@fuel-ts/testcases
I mistakenly marked it as `private`, breaking the last release.
This is the hotfix for it.
> Thanks @LuizAsFight for the heads up. 🙌
> fix: adjust `testcases` configs

- .changeset/young-gorillas-destroy.md
- packages/abi-coder/package.json
- packages/abi-typegen/package.json
- packages/abi-typegen/src/templates/predicate/factory.test.ts
- packages/address/package.json
- packages/constants/package.json
- packages/contract/package.json
- packages/fuels/package.json
- packages/hasher/package.json
- packages/hdwallet/package.json
- packages/interfaces/package.json
- packages/keystore/package.json
- packages/math/package.json
- packages/merkle-shared/package.json
- packages/merkle/package.json
- packages/merklesum/package.json
- packages/mnemonic/package.json
- packages/predicate/package.json
- packages/program/package.json
- packages/providers/package.json
- packages/script/package.json
- packages/signer/package.json
- packages/sparsemerkle/package.json
- packages/transactions/package.json
- packages/versions/package.json
- packages/wallet-manager/package.json
- packages/wallet/package.json
- packages/wordlists/package.json
When using the `exports` field in `package.json` files, the `default` key must [always be the last](https://nodejs.org/api/packages.html#conditional-exports):
In my [last PR](https://github.com/FuelLabs/fuels-ts/pull/810), I added the `types` keys after the `default`, breaking all packages.
To be free from the object's ordering shenanigans, I'm changing all `default` entries to `import`, which should have the same effect without being subjected to a specific ordering.
> fix: exports configs in packages' json files

- .changeset/empty-waves-appear.md
- packages/wallet/src/account.ts
- packages/wallet/src/base-unlocked-wallet.ts
- packages/wallet/src/configs.ts
- packages/wallet/src/wallet.test.ts
- packages/wallet/src/wallet.ts
> fix: adjusting constants evaluation by removing usage of `process.env`

- scripts/changeset-version-with-docs.ts
The version's auto-commit script should not abort the Github action when the working tree is clean.
- https://github.com/FuelLabs/fuels-ts/actions/runs/4555333373/jobs/8034228312#step:7:46
I've simply moved the related code block outside the `-e`~`+e` range.
> fix: ignoring possible git errors when auto-committing generated versions file

- .github/workflows/release.yaml
This tries to fix the CI error from the last merge.
I am removing the `permissions` item from the `release.yaml` workflow to avoid all other permissions being set as `none`
> ref 1: https://github.com/FuelLabs/fuels-ts/actions/runs/4574396787/jobs/8079391507#step:7:167
> ref 2: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview
> fix: remove permissions item from release workflow

- .changeset/curvy-doors-promise.md
- .changeset/funny-balloons-cheat.md
- apps/docs/.vitepress/config.ts
- apps/docs/src/guide/contracts/transaction-dependency-estimation.md
- packages/providers/src/provider.ts
- packages/wallet/src/account.test.ts
- packages/wallet/src/account.ts
- packages/wallet/src/base-unlocked-wallet.ts
- packages/wallet/src/wallet-unlocked.test.ts
Summary
As discussed https://github.com/FuelLabs/fuels-ts/issues/701#issuecomment-1518139934, this PR renames the addMissingVariables helper to estimateTxDependencies for better consistency with the Rust SDK, and adds a docs page for transaction dependency estimation.
Re-opened this PR in place of #924 because of some issues with merge conflicts and the PR's base branch.
Closes https://github.com/FuelLabs/fuels-ts/issues/701
> refactor: rename `addMissingVariables` to `estimateTxDependencies`, add docs

- .changeset/cuddly-moles-perform.md
- packages/fuels/package.json
Removing misplaced entry-point _(residual from Typegen configs duplication)_.
> fix: package configs for `fuels`

- .github/workflows/pr-release.yaml
> feat: Replace workflows deprecated methods

- .changeset/flat-coats-swim.md
- packages/providers/src/transaction-request/input.ts
`value.data` is a `BytesLike`, which means it can be a string. but it was manipulated like if it was always an array, resulting in incorrect encoding when receiving an empty string, for example: `0x`.
this PR address the issue and apply same pattern used to `value.predicate` and `value.predicateData`, which probably was probably forgotten to be added to `value.data` also
ps: this PR is a blocker for bridge project
> fix: inputify should manipulate value.data as possibly string

- .github/workflows/md-lint.yaml
This PR limits the workflow _"Lint markdown files"_ to run only on new PR pushes. We don't need it to run when we change the PR `title` or `description` — the same couldn't be said about the `PR lint` workflow, which validates the PR `title`.
> fix: limiting triggers for markdown lint workflow

- .changeset/smooth-cameras-study.md
- packages/fuel-gauge/src/coverage-contract.test.ts
- packages/providers/src/message.ts
- packages/providers/src/operations.graphql
- packages/providers/src/provider.test.ts
- packages/providers/src/provider.ts
- packages/providers/src/transaction-request/input.ts
- packages/transactions/src/coders/input.test.ts
- packages/transactions/src/coders/input.ts
input message is broken, this PR fixes it by:
- adding `messageId` field to InputMessage
- add to messageFragment in operations.graphql, allowing to query it from node
- include in decoder
- include `messageId` when adding resources to a transaction
- fix tests to use `messageId` in input
Closes [FRO-195](https://linear.app/fuel-network/issue/FRO-195/after-sending-transaction-its-showing-incorrect-in-transaction-screen)
> fix: add messageId to input message decoder

- .husky/pre-push
- package.json
- pnpm-lock.yaml
Removed `pnpm lint` from `pre-push.sh` after discussions with the team. We agree that the `pnpm lint` in the workflows is enough.
> chore: remove pnpm lint from pre-push

- .changeset/serious-pans-search.md
- packages/providers/src/operations.graphql
- packages/providers/src/provider.ts
- packages/providers/src/transaction-response/transaction-response.ts
- packages/providers/src/utils/fee.test.ts
- packages/providers/src/utils/fee.ts
- packages/providers/test/provider.test.ts
Pretty much what the title says. 
The `calculateTransactionFee` method was updated based on the version used by `fuels-wallet`
> fix: calculate transaction fee

- .changeset/shy-students-rush.md
- packages/providers/src/transaction-request/transaction-request.ts
On this PR;
- Ensure `hasPredicate` method returns true to any input that contains a predicate field
> fix: predicate check on estimateTxDependencies

- .changeset/odd-laws-change.md
- .github/workflows/pr-release.yaml
- packages/crypto/src/browser/stringFromBuffer.ts
- packages/providers/src/transaction-summary/index.ts
The current approach was refactored by me on #1157
It seems it does not always work, therefore, I am rolling back to the previous approach instead.
> fix: decoding for base64 at `stringFromBuffer` browser version

- .changeset/green-badgers-roll.md
- .github/workflows/pr-release.yaml
- packages/providers/src/provider.ts
- packages/providers/src/transaction-summary/assemble-transaction-summary.ts
- packages/providers/src/transaction-summary/get-transaction-summary.ts
- packages/providers/src/utils/fee.test.ts
- packages/providers/src/utils/fee.ts
> UPDATED
This PR introduces and exports two new helper functions: `calculateTransactionFeeForScript` and `calculateTransactionFeeForContractCreated`. These helpers are designed to streamline the process of calculating transaction fees for specific scenarios. The existing `calculateTransactionFee` function will remain available and will make use of these two new helpers.
The motivation behind creating these two new helper functions is to simplify the transaction fee calculation process for users who already know the type of transaction they are dealing with.  Currently, users must provide additional parameters to `calculateTransactionFee`, which can be cumbersome if those parameters are irrelevant to the specific transaction type.
> refactor: split `calculateTransactionFee` into 2 helpers

- .changeset/twenty-cups-shop.md
- packages/wallet/src/test-utils/launchNode.ts
> chore: Add and export explicit return types for `launchNodeAndGetWallets` and `launchNode`

- .changeset/olive-berries-happen.md
- packages/wallet/src/test-utils/launchNode.ts
> fix: make sure `pid` is defined before attempting to kill `launchNodeAndGetWallets`

- .changeset/gold-planets-double.md
- apps/docs-snippets/src/guide/predicates/index.test.ts
- apps/docs-snippets/src/guide/predicates/predicate-with-configurable.test.ts
- apps/docs-snippets/src/guide/predicates/send-and-spend-funds-from-predicates.test.ts
- packages/abi-typegen/src/templates/predicate/factory.hbs
- packages/abi-typegen/test/fixtures/templates/predicate-with-configurable/factory.hbs
- packages/abi-typegen/test/fixtures/templates/predicate/factory.hbs
- packages/fuel-gauge/src/contract.test.ts
- packages/fuel-gauge/src/doc-examples.test.ts
- packages/fuel-gauge/src/predicate-conditional-inputs.test.ts
- packages/fuel-gauge/src/predicate/predicate-arguments.test.ts
- packages/fuel-gauge/src/predicate/predicate-configurables.test.ts
- packages/fuel-gauge/src/predicate/predicate-estimations.test.ts
- packages/fuel-gauge/src/predicate/predicate-evaluations.test.ts
- packages/fuel-gauge/src/predicate/predicate-invalidations.test.ts
- packages/fuel-gauge/src/predicate/predicate-with-contract.test.ts
- packages/fuel-gauge/src/predicate/predicate-with-script.test.ts
- packages/fuel-gauge/src/vector-types.test.ts
- packages/predicate/src/predicate.ts
- packages/predicate/test/features/predicate-functions.test.ts
- packages/predicate/test/features/predicate-transactions.test.ts
- packages/providers/src/provider.ts
We don't need to pass in the `chainId` explicitly now since we are passing in a `Provider` already. We can extract the `chainId` from the `Provider`.
Closes #1261
> refactor!: remove `chainId` from the `Predicate` constructor

- .changeset/moody-hats-grow.md
- packages/abi-coder/src/constants.ts
- packages/abi-coder/src/index.ts
- packages/predicate/src/predicate.ts
- packages/program/src/contract-call-script.ts
- packages/program/src/functions/base-invocation-scope.ts
- packages/program/src/script-request.ts
- packages/providers/src/transaction-response/transaction-response.ts
- packages/providers/src/transaction-summary/assemble-transaction-summary.test.ts
- packages/providers/src/transaction-summary/assemble-transaction-summary.ts
- packages/providers/src/transaction-summary/call.ts
- packages/providers/src/transaction-summary/get-transaction-summary.ts
- packages/providers/src/transaction-summary/operations.test.ts
- packages/providers/src/transaction-summary/operations.ts
- packages/providers/src/transaction-summary/types.ts
> refactor: purge the usage of the hardcoded constant `VM_TX_MEMORY`

- .changeset/strong-garlics-prove.md
- packages/providers/src/provider.ts
- packages/providers/src/transaction-summary/assemble-transaction-summary.ts
- packages/providers/src/utils/calculate-fee.test.ts
- packages/providers/src/utils/calculate-fee.ts
Made `CalculateTransactionFee` to return `minFee` and `maxFee`. 
These values are relevant when calculating the amount of funds a Transaction Request needs before being submitted to the chain
**EDIT**
On [1307](https://github.com/FuelLabs/fuels-ts/pull/1307), I did not return the `maxFee` because I was under the impression that it was not relevant, since the actual fee deducted from the user's wallet was always the `minFee`.
However, I've recently become aware that the [VM always uses](https://github.com/FuelLabs/fuel-vm/blob/94677aa1cfa5a150368c4820a8a757baac479e1f/fuel-vm/src/checked_transaction/balances.rs#L73-L78) the `maxFee` value to estimate if the transaction has enough balances to cover the fee.
In other words, we need `maxFee` in order to properly fund a transaction before …
> fix: update calculate fee outputs

- .changeset/config.json
- .changeset/light-cameras-tease.md
- apps/docs/src/guide/cli/commands.md
- packages/fuels/src/cli.ts
- packages/fuels/src/cli/commands/build/index.ts
- packages/fuels/src/cli/commands/dev/index.ts
- packages/fuels/src/cli/commands/dev/startFuelCore.ts
- packages/fuels/src/cli/commands/withConfig.ts
- packages/fuels/test/features/build.test.ts
- packages/fuels/test/features/dev.test.ts
- packages/fuels/test/utils/mockStartFuelCore.ts
- packages/fuels/test/utils/runCommands.ts
> feat: add `deploy` flag to fuels cli `build` command

- .changeset/kind-glasses-brake.md
- apps/docs-snippets/src/guide/predicates/send-and-spend-funds-from-predicates.test.ts
- apps/docs/src/guide/predicates/send-and-spend-funds-from-predicates.md
- packages/predicate/package.json
- packages/predicate/src/predicate.ts
- packages/wallet/src/account.test.ts
- packages/wallet/src/account.ts
- pnpm-lock.yaml
As a part of #1451, this PR adds a new helper `getTransferTxId` for predicates which lets you calculate the transaction ID for a `Predicate.transfer` transaction, before actually sending it.
> feat: add `Predicate.getTransferTxId` helper

- .changeset/kind-doors-grow.md
- packages/fuels/src/cli/commands/deploy/deployContract.ts
- packages/fuels/src/cli/commands/deploy/index.ts
- packages/fuels/src/cli/config/forcUtils.ts
Closes #1472 
If we don't auto-load these storage slots, some contracts will revert because of improper/missing initialization of storage slots.
> fix: auto-load storage slots in `fuels deploy`

- .changeset/many-carrots-draw.md
- packages/fuels/package.json
- packages/fuels/src/cli/commands/dev/startFuelCore.ts
- pnpm-lock.yaml
This PR fixes a bug where the initial approach used by `startFuelCore` to locate the `fuels-core` binaries was only working for `pnpm`. This is now package manger agnostic with this PR.
> fix: make `startFuelCore` package manager agnostic

- .changeset/mean-phones-tickle.md
- packages/fuels/src/cli.ts
- packages/fuels/src/cli/commands/build/buildSwayPrograms.ts
- packages/fuels/src/cli/commands/dev/startFuelCore.ts
- packages/fuels/src/cli/utils/findBinPath.ts
- packages/fuels/src/cli/utils/findPackageRoot.ts
Similar to #1477, but also adds (possible) support for [bun](https://bun.sh]), which has a different way of structuring binaries inside of `node_modules`.
> fix: bin path for `fuels-forc` in fuels CLI, add support bun's structure

- .changeset/spotty-berries-cry.md
- packages/providers/src/transaction-summary/input.ts
- packages/providers/src/transaction-summary/operations.test.ts
- packages/providers/src/transaction-summary/operations.ts
The current implementation of `getContractCreatedOperations` only checks by inputs of type `Coin` with the new implementation if accounts for coin and message.
This issue is affecting also beta-4 versions, would be good to have a patch for the older versions also. But maybe as we don't have this support for now we are going to get it only on beta-5. cc: @arboleya 
closes: #1634
> fix: contract created operation with input message

- .changeset/plenty-seals-pay.md
- packages/predicate/src/index.ts
- packages/predicate/src/utils/getPredicateRoot.test.ts
- Close: https://github.com/FuelLabs/fuels-ts/issues/1646
> feat: export `getPredicateRoot` from `predicate` package

- .changeset/beige-actors-march.md
- packages/forc/lib/bin.js
- packages/forc/lib/index.js
- packages/forc/lib/install.js
- packages/forc/lib/shared.js
- packages/forc/package.json
- packages/fuel-core/lib/bin.js
- packages/fuel-core/lib/index.js
- packages/fuel-core/lib/install.js
- packages/fuel-core/lib/shared.js
- packages/fuel-core/package.json
- pnpm-lock.yaml
A couple of commands were broken, like:
```ts
import fs from 'fs/promises';
fs.rmSync(...);
```
But there's no `<cmd>Sync()` methods in `fs/promises`.
I also used the opportunity to standardize a couple of things.
I had problems with the TAR package, saying the `tar` files were invalid.
Since we won't support Windows soon, I removed them and rolled back the original commands.
> fix: bin installation from git

- package.json
- pnpm-lock.yaml
Closes #1770 
upgrade version of `webdriverio` from `1.27.0` to `1.32.0`
> chore: upgrade version of webdriverio

- .changeset/little-timers-melt.md
- templates/nextjs/src/pages/index.tsx
Added 'center' class name to 'items-' utility class.
the syntax error: https://github.com/FuelLabs/fuels-ts/blob/master/templates/nextjs/src/pages/index.tsx?plain=1#L51
> fix: missing class name fix for items utility class

- .changeset/brown-dingos-grow.md
- packages/create-fuels/src/bin.ts
This was disabled unintentionally when the internal API was changed recently.
> fix: re-enable auto-install of dependencies when `create-fuels` is run

- .github/workflows/release.yaml
- .github/workflows/test.yaml
Fixes:
- Broken coverage report (e.g. [this](https://github.com/FuelLabs/fuels-ts/actions/runs/8362381017/job/22893369897?pr=1883#step:9:34))
- Title of changeset PR from "ci(changesets): versioning packages for branch ``" to :ci(changesets): versioning packages for branch `master`"
Note: I commented out the coverage part in https://github.com/FuelLabs/fuels-ts/pull/1908/commits/9ab6863573fa1fe899ecd751f91a71092f50e9eb to get `master` to upload its `coverage-artifact` and I'll do a subsequent PR to uncomment it.
> fix: broken coverage report and changeset PR title

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- scripts/changeset/update-changelog.mts
The script ran on the `changesets-release/master` branch which _doesn't have_ any changesets on it because it deletes them. It should run on `master`, hence `git checkout master`.
I also fixed the logic for updating the release's body. It now finds its corresponding changeset PR and just copies its body.
> fix: changelogs not showing up on changesets PR

- .changeset/ten-games-lay.md
- .github/workflows/breaking-change-pr-release.yaml
Fix this: https://github.com/FuelLabs/fuels-ts/actions/runs/8394068112/job/22990387566?pr=1892
> chore: fix `backstick` error on breaking change workflow

- scripts/changeset/update-changelog.mts
The changelog prettifying step [failed](https://github.com/FuelLabs/fuels-ts/actions/runs/8421458063/job/23058461552#step:9:20) because of the tag missing from local git.
closes #1938.
> fix: fetch just-published tag

- .changeset/ten-geese-trade.md
- apps/docs-snippets/src/guide/cookbook/custom-transactions-contract-calls.test.ts
- apps/docs-snippets/src/guide/scripts/script-custom-transaction.test.ts
- apps/docs/.vitepress/config.ts
- Added missing semi-colons to the imports.
- `Errors` documentation section, now nested under the `basics` parent.
> docs: fix imports and reordered errors

- .changeset/tame-beans-type.md
- packages/account/src/providers/provider.ts
- packages/account/src/providers/transaction-request/script-transaction-request.ts
- packages/account/src/providers/transaction-request/types.ts
- packages/account/src/providers/transaction-response/getDecodedLogs.ts
- packages/account/src/providers/transaction-response/transaction-response.ts
- packages/fuel-gauge/src/advanced-logging.test.ts
- packages/fuel-gauge/src/contract-factory.test.ts
- packages/program/src/functions/base-invocation-scope.ts
- packages/program/src/functions/invocation-results.ts
- packages/program/src/types.ts
- packages/program/src/utils.ts
- Close: https://github.com/FuelLabs/fuels-ts/issues/1941
> feat: decode logs from TXs submitted outside `BaseInvocationScope`

- .changeset/tall-bees-move.md
Original PR is #1963. This PR just changes its changeset to mark it as a breaking change.
> chore!: reset base `forc` version to `0.49.3` except for experimental builds

- .changeset/nasty-clocks-share.md
- packages/fuels/src/cli/commands/deploy/createWallet.ts
This was failing locally for those not using Linux (hence why it works in CI).
I tracked it down to this cause.
> chore: handling `EADDRNOTAVAIL` errors on top of `ECONNREFUSED`

- .changeset/silver-phones-walk.md
- README.md
- apps/docs/src/guide/fuels/commands.md
- packages/abi-typegen/README.md
Fixes dead links for `abi-typegen`
https://github.com/FuelLabs/fuels-ts/actions/runs/8517995686/job/23329401712?pr=1980#step:4:265
> docs: updated abi-typegen to typegen for links

- .changeset/slow-dancers-relax.md
- packages/abi-coder/src/Interface.ts
- packages/contract/src/contract-factory.ts
- packages/contract/src/util.ts
- packages/errors/README.md
- packages/errors/src/error-codes.ts
- packages/errors/src/fuel-error.test.ts
Related to #1556 
---
- Removed redundant error codes.
> chore: remove redundant error codes

- .changeset/brave-rice-march.md
- packages/abi-coder/src/Interface.ts
- packages/fuel-gauge/src/experimental-contract.test.ts
- packages/fuel-gauge/src/utils.ts
- packages/fuel-gauge/test/fixtures/forc-projects-experimental/contract-echo/src/main.sw
Relates to #1672.
I had incorrectly assumed that configurable constants were included for `v1` encoding. They are currently [unsupported](https://github.com/FuelLabs/sway/issues/5727).
This PR removes support at the encoding entry point for configurables, and introduces a test that includes both `v0` configurable encoding and `v1` param encoding.
> feat!: deprecate multiple encoding version support for configurable constants

- scripts/changeset/changeset-version-with-docs.ts
Fixes how `getBuiltinVersions` is updated. This will update [`getBuiltinVersions` on the current changesets PR](https://github.com/FuelLabs/fuels-ts/pull/2072/files#diff-f34e8f56f6328b8b21d0b488f36cc3d07fd8125615629b65d01295009ff02266R5) to the proper value on the changeset PR.
If you want to test the fix locally, run the following on `master`:
- `pnpm tsx packages/versions/scripts/rewriteVersions.ts`
- Notice that it changes to `0.80.0`. This is because we have a version mismatch between our `master`'s [`packages/fuels/package.json`](https://github.com/FuelLabs/fuels-ts/blob/764b37eac34647d653aceb3f681edccebc550095/packages/fuels/package.json#L3) and [`getBuiltinVersions`](https://github.com/FuelLabs/fuels-ts/blob/764b37eac34647d653aceb3f681edccebc550095/packages/versions/src/lib/getBuilt …
> fix: improper update of `getBuiltinVersions`

- .github/workflows/pr-release.yaml
It was committed by mistake; one needs to uncomment it before merging:
https://github.com/FuelLabs/fuels-ts/blob/5daeea42b83944e9fc758012f235e41e7aa7bdff/.github/workflows/pr-release.yaml#L11
We could have a routine for automating this.
**EDIT**: _Created an [issue](https://github.com/FuelLabs/fuels-ts/issues/2119) for it._
> chore: disabling PR auto-release

- .changeset/sharp-pillows-film.md
- .github/actions/ci-setup/action.yaml
- .github/actions/test-setup/action.yaml
- .github/workflows/breaking-change-pr-release.yaml
- package.json
The [lint step fails on CI](https://github.com/FuelLabs/fuels-ts/actions/runs/8757757991/job/24037100858?pr=2117) but this isn't happening for me locally. I am running `pnpm` `9.0.2` so figured I would upgrade it across the board.
> build: upgrade `pnpm` version

- .changeset/tame-icons-film.md
- packages/abi-coder/src/encoding/coders/v1/VecCoder.test.ts
- packages/abi-coder/src/encoding/coders/v1/VecCoder.ts
The work in #2018 made a `UInt8Array` a valid input for for `VecCoder.encode`. This is useful for working with bytecode, where the function likely accepts a `Vec<u8>` and the input would be passed as _arrayified_ binary, so requiring a `number[]` is poor DX. 
This feature was not brought across to `V1`, it was probably missed due to the timing overlap. This PR introduces that change to `V1` encoding.
> feat: `VecCoder@v1` accepts `UInt8Array` as encode input

- .changeset/olive-meals-love.md
- packages/abi-coder/src/encoding/coders/ArrayCoder.ts
- packages/abi-coder/src/encoding/coders/EnumCoder.ts
- packages/abi-coder/src/encoding/coders/StructCoder.ts
- packages/abi-coder/src/encoding/coders/TupleCoder.ts
- packages/abi-coder/src/encoding/coders/VecCoder.ts
- packages/fuel-gauge/src/options.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/options/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/options/src/main.sw
Closes #2321 
For `v0` encoding, an option would contain a `WORD_SIZE` for the enum case key (`Some` or `None`) and the property space for the value (i.e `u64` would be another `WORD_SIZE`. Even if the value was `None`, we would still receive the expected value property space, meaning we could validate correct for both values. However in `v1`, `None` will now only return the case bytes, and no value bytes. Meaning we can no longer validate the expected byte length before checking the case value.
We are still validating at the option value level (i.e. `Option<u8>` will be validated in the `NumberCoder` so we should not be too concerned about underflow/overflow here, but there are definitely improvements that could be made, that I'll investigate …
> feat!: remove nested option size validation

- .changeset/shiny-phones-compete.md
- packages/abi-coder/src/encoding/coders/ArrayCoder.ts
- packages/abi-coder/src/encoding/coders/EnumCoder.ts
- packages/abi-coder/src/encoding/coders/StructCoder.ts
- packages/abi-coder/src/encoding/coders/TupleCoder.ts
- packages/abi-coder/src/encoding/coders/VecCoder.ts
- packages/abi-coder/src/utils/utilities.test.ts
- packages/abi-coder/src/utils/utilities.ts
- packages/fuel-gauge/src/options.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/options/src/main.sw
Extension of #2322 to include deeply nested search for `option`.
> feat: find deeply nested `option` coders

- .changeset/kind-flowers-chew.md
- packages/abi-coder/src/encoding/coders/EnumCoder.ts
- packages/fuel-gauge/src/options.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/options/src/main.sw
Closes #2335 
#2322 and #2325 removed length validation for nested options. We should also disable the enum level length validation, where the coder itself is an `enum Option`.
> feat: disable `option` length validation at `enum Option` level

- .changeset/breezy-owls-sing.md
- packages/abi-typegen/src/abi/types/EnumType.ts
- packages/abi-typegen/src/templates/contract/dts.hbs
- packages/abi-typegen/src/templates/utils/formatEnums.test.ts
- packages/abi-typegen/src/templates/utils/formatEnums.ts
- packages/abi-typegen/test/fixtures/forc-projects/full/src/main.sw
- packages/abi-typegen/test/fixtures/templates/contract/dts.hbs
I found this issue after running `pnpm tsc --noEmit` on typegen outputs of our `fuel-gauge` test suite.
> feat: support generic enums in `typegen`

- .changeset/fast-deers-turn.md
- packages/abi-typegen/src/runTypegen.test.ts
- packages/abi-typegen/src/templates/predicate/factory.hbs
- packages/abi-typegen/src/templates/predicate/factory.ts
- packages/abi-typegen/src/templates/script/factory.hbs
- packages/abi-typegen/src/templates/script/factory.ts
- packages/abi-typegen/test/fixtures/forc-projects/predicate/src/main.sw
- packages/abi-typegen/test/fixtures/forc-projects/script/src/main.sw
- packages/abi-typegen/test/fixtures/templates/predicate/factory.hbs
- packages/abi-typegen/test/fixtures/templates/script/factory.hbs
I found this issue after running `pnpm tsc --noEmit` on typegen outputs of our `fuel-gauge` test suite.
> fix: `typegen` generic enums and `./common` import (predicates, scripts)

- .changeset/hot-pumpkins-applaud.md
- .github/workflows/pr-validate-changesets.yaml
master is [currently failing](https://github.com/FuelLabs/fuels-ts/actions/runs/9259587381/job/25471817316) due to an [unnecessary validation of changesets](https://github.com/FuelLabs/fuels-ts/pull/2305/files#diff-900c14db30cf12f70161bd32e69363c032130443d4f052508d970d7d2fbfa472R3-R7) merged in #2035
> ci: fix workflow run for changeset validation on master

- .changeset/rotten-tomatoes-draw.md
- packages/fuels/src/index.test.ts
- packages/fuels/src/index.ts
> chore: exporting `FuelError` class in umbrella package

- .changeset/modern-students-poke.md
- .github/workflows/pr-release.yaml
- packages/abi-coder/src/encoding/coders/EnumCoder.ts
- packages/fuel-gauge/src/options.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/options/src/main.sw
Currently, we are validating the size of an `enum` against the [maximum](https://github.com/FuelLabs/fuels-ts/blob/5a6ca46ef46b856db780562b455dd9d742977404/packages/abi-coder/src/encoding/coders/EnumCoder.ts#L38-L41) size of a child value. If an `enum` contains both a `u8` and a `b512` and we pass the `u8` value, we'd expect this to throw for underflow. It is not, as we are incorrectly [validating](https://github.com/FuelLabs/fuels-ts/blob/5a6ca46ef46b856db780562b455dd9d742977404/packages/abi-coder/src/encoding/coders/EnumCoder.ts#L83) against the value size rather than the `encodedLength` which does not include the case length. 
This PR now correctly checks for `encodedLength`, as well as setting this value to the size of the smallest coder. We will then do another size check once we …
> fix: `enum` size validation

- .changeset/fifty-worms-sleep.md
- .github/dependabot.yml
- .github/workflows/pr-validate-changesets.yaml
- Closes https://github.com/FuelLabs/fuels-ts/issues/2673
This PR creates a `.netrc` file for handling autologin for github credentials in order to be able to commit the changesets in the consequent job. 
> [!NOTE]
> - This also temporarily reduces the amount of pull requests Dependabot can open for the purposes of testing this PR over the next few days.
> - This also increases the frequency with which dependabot will open PRs.
> ci: introduce github credentials for committing changesets

- .changeset/slimy-moons-draw.md
- .github/workflows/test.yaml
> chore: triggerable `devnet` e2e tests

- .changeset/gorgeous-donuts-stare.md
- packages/contract/src/test-utils/launch-test-node.ts
The following code yields a compilation error*:
```ts
import { launchTestNode } from 'fuels/test-utils';
export const myHelper = async () => {
const node = await launchTestNode();
const doMore = 'stuff';
return { doMore, node };
};
```
Exporting the interfaces tied to `launchTestNode` fixes the issue.
*The compilation error is:
```
Exported variable 'myHelper' has or is using name 'DeployContractConfig' from external module "/fuels-ts/packages/contract/dist/test-utils/launch-test-node" but cannot be named
Exported variable 'myHelper' has or is using name 'LaunchTestNodeReturn' from external module "/fuels-ts/packages/contract/dist/test-utils/launch-test-node" but cannot be named
⚠ Error (TS4023) | 
Exported variable myHelper has or is using name DeployContractConfig from external module …
```
> fix: export `launchTestNode` interfaces

- .github/workflows/pr-validate-changesets.yaml
> fix: dependabot creates multiple changesets

- .changeset/rotten-forks-share.md
- apps/create-fuels-counter-guide/src/app/page.tsx
- apps/create-fuels-counter-guide/src/hooks/useFaucet.tsx
- apps/create-fuels-counter-guide/src/lib.ts
- templates/nextjs/src/app/page.tsx
- templates/nextjs/src/hooks/useFaucet.tsx
- templates/nextjs/src/lib.ts
> chore: replace `create-fuels` hardcoded values with constants

- .changeset/soft-cycles-do.md
- packages/contract/src/test-utils/launch-test-node.ts
- packages/fuel-gauge/src/launch-test-node-types.test.ts
- closes #2754
Contracts inferred from an array of factories were inferred as a discriminated union of all factory contract returns instead of matching the sequence of contract factories in the `contractConfigs` array:
```ts
using launched = await launchTestNode({
contractsConfigs: [
{ deployer: AdvancedLoggingAbi__factory, bytecode: '' },
{ deployer: CallTestContractAbi__factory, bytecode: '' },
],
});
const {
contracts: [c1, c2],
} = launched;
// before: c1 and c2 are both AdvancedLoggingAbi | CallTestContractAbi
// after: c1 is AdvancedLoggingAbi, c2 is CallTestContractAbi
```
> fix: `launchTestNode` multiple contracts type inference

- apps/docs/src/guide/wallets/connectors.md
Replace dead link. Previous link don't exist anymore because the Fuel Connectors wiki page was moved to https://github.com/FuelLabs/fuel-connectors repository.
> chore: fix connectors doc

- .changeset/rare-ducks-sort.md
- packages/create-fuels/src/cli.ts
- packages/create-fuels/src/lib/setupProgram.test.ts
- packages/create-fuels/src/lib/setupProgram.ts
- Closes #2778
-  `create-fuels` now installs dependencies by default
> fix: `create-fuels` install dependencies by default

- .changeset/sweet-schools-jump.md
- .github/workflows/release.yaml
- apps/docs/.vitepress/config.ts
- Closes #2455
- PR now deploy docs to [Vercel](https://github.com/FuelLabs/fuels-ts/pull/2780#issuecomment-2233208529)
- Removed all related GitHub pages from the release
> chore: removed GitHub pages deployment

- .changeset/cyan-chicken-jam.md
- apps/demo-wallet-sdk-react/package.json
- apps/demo-wallet-sdk-react/pages/_app.tsx
- pnpm-lock.yaml
- Closes #2397
- Fixed the build error for `demo-wallet-sdk-react` (see [here](https://github.com/FuelLabs/fuels-ts/actions/runs/10011061335/job/27674200406?pr=2800#step:3:1311))
- Upgrade `@fuel/connectors` to `0.8.1`
> fix: build error for `demo-wallet-sdk-react`

- .changeset/mighty-crews-vanish.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/test-utils/launchNode.ts
- Closes #2813 
In the previous solution, the `minGasPrice` was already defined by default. This PR fixes it by basing it on the `params`.
> fix: allow setting min gas price in `launchNode` args

- .github/pull_request_template.md
> chore: adding line breaks to PR template comments

- .changeset/cyan-doors-tickle.md
- apps/docs-snippets/src/utils.ts
- packages/account/src/account.ts
- packages/account/src/providers/provider.ts
- packages/account/src/test-utils/seedTestWallet.ts
- packages/account/src/wallet/base-wallet-unlocked.ts
- packages/contract/src/contract-factory.ts
- packages/fuel-gauge/src/await-execution.test.ts
- packages/fuel-gauge/src/predicate/utils/predicate/fundPredicate.ts
- packages/fuel-gauge/src/transaction-response.test.ts
- packages/program/src/functions/base-invocation-scope.ts
- Closes https://github.com/FuelLabs/fuels-ts/issues/2821
- Remove the `awaitExecution` flag and its associated functionality
This PR removes the `awaitExecution` flag and its functionality. After the changes introduced in https://github.com/FuelLabs/fuels-ts/pull/2597 and https://github.com/FuelLabs/fuels-ts/pull/2692 the SDK no longer uses this functionality internally. Although users could still manually submit transactions using the `awaitExecution` flag after https://github.com/FuelLabs/fuels-ts/pull/2597 and https://github.com/FuelLabs/fuels-ts/pull/2692, this is no longer supported.
It is no longer possible to submit transactions using the `awaitExecution` flag and wait for the transaction to be processed at submission:
```ts
// before
await …
```
> chore!: remove `awaitExecution` functionality

- .changeset/pink-walls-roll.md
- apps/docs-snippets/src/guide/contracts/minted-token-asset-id.test.ts
- Updated documentation to reflect the correct usage of `getMintedAssetId` - passing the `contractId` and `subId`
https://github.com/FuelLabs/fuels-ts/blob/a7ef2c59d32400316de1652a590d5d15db7daed4/packages/transactions/src/coders/receipt.ts#L770
- Using `launchTestNode` in related test.
> docs: fix `getMintedAssetId` example

- .changeset/three-candles-appear.md
- packages/abi-typegen/src/templates/contract/dts.hbs
- packages/abi-typegen/test/fixtures/templates/contract-with-configurable/dts.hbs
- packages/abi-typegen/test/fixtures/templates/contract/dts.hbs
- Closes #2842 
Just prefixing the hbs file with the `export` keyword.
> fix: export interfaces in typegen

- .changeset/twenty-donuts-sin.md
- scripts/changeset/get-full-changelog.mts
- closes #2860
There are special cases that follow a different flow (e.g. https://github.com/FuelLabs/fuels-ts/commit/16ee1bfe66733551d00f0a76c21e8a09ea33006f). They should be ignored in the changelogs.
> fix: ignore unreachable PRs when formatting changelogs

- packages/abi-coder/src/encoding/coders/OptionCoder.test.ts
- packages/abi-coder/src/encoding/coders/OptionCoder.ts
- packages/abi-coder/src/encoding/coders/StructCoder.test.ts
- packages/abi-coder/src/encoding/strategies/getCoderV1.ts
- packages/abi-coder/src/utils/constants.ts
- #2856 was throwing the following error in some test cases, which was [investigated](https://github.com/FuelLabs/fuels-ts/pull/2856/files#r1698470655). Implemented the suggested solution and all test cases are green.
```console
TypeError: Cannot use 'in' operator to search for 'Some' in None
```
- Reverted the [commit](https://github.com/FuelLabs/fuels-ts/pull/2856/commits/45f3ef2bac2999f876e1390f0670ac7df5737f8b) that "fixed" the issue.
- Pulled over the OptionCoder test from #2869 to test the change.
> fix: option coder decoding incorrect value

- .changeset/rude-goats-smile.md
- packages/account/src/test-utils/setup-test-provider-and-wallets.test.ts
- packages/account/src/test-utils/test-message.ts
- packages/fuel-gauge/src/transaction-summary.test.ts
This PR updates the default value of the `data` property in [TestMessage](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/test-utils/test-message.ts) to an empty string. This change ensures that a new instance of `TestMessage` is spendable by default when the `data` property is not provided.
> chore: default TestMessage to be spendable

- .changeset/stupid-planets-joke.md
- apps/docs/src/guide/errors/index.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- packages/errors/src/error-codes.ts
- Closes https://github.com/FuelLabs/fuels-ts/issues/2419
> chore: add validation for TX max outputs exceeded

- .changeset/yellow-eagles-breathe.md
- apps/docs-snippets/src/guide/testing/launching-a-test-node.test.ts
- apps/docs/src/guide/testing/test-node-options.md
- packages/account/src/test-util.test.ts
- packages/account/src/test-utils.ts
- packages/account/src/test-utils/setup-test-provider-and-wallets.test.ts
- packages/account/src/test-utils/setup-test-provider-and-wallets.ts
- packages/account/src/test-utils/test-asset-id.ts
- packages/account/src/test-utils/wallet-config.test.ts
- packages/account/src/test-utils/wallet-config.ts
- packages/fuel-gauge/src/doc-examples.test.ts
- Closes #2904
- Renamed testing class `AssetId` to `TestAssetId`
- Renamed testing class `AssetId` to `TestAssetId`
```ts
// Before
import { AssetId } from 'fuels/test-utils';
const [assetA] = AssetId.random();
```
```ts
// After
import { TestAssetId } from 'fuels/test-utils';
const [assetA] = TestAssetId.random();
```
> chore!: renamed `AssetId` to `TestAssetId`

- .github/pull_request_template.md
I considered re-wording the PR tasklist, so all items must **_always_** be ☑️ completed.
This way, all tasks must be completed for a PR to be ready, adding consistency and removing ambiguity.
The tasklist 👇 for this PR already follows the new model for demo purposes:
> chore: updating pull request tasklist

- packages/account/src/connectors/fuel.ts
For testing via NPM (unauthorized)
Source: #2940
> fix: flakey connectors on re render

- .changeset/smart-seals-care.md
- packages/account/src/providers/fuel-graphql-subscriber.ts
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- packages/account/src/providers/transaction-response/transaction-response.ts
- packages/fuel-gauge/src/edge-cases.test.ts
I moved `FuelGraphqlSubcriber` instantiation to be async as a preparatory step for #2936. I tried introducing the solution for that issue in #2962, commit https://github.com/FuelLabs/fuels-ts/pull/2962/commits/80511131b68754288f7e686fc040413e8ea14141, but I wasn't happy with the solution so I reverted it and created this to give myself room to figure out a solution.
This change is necessary for the usage of `submitAndAwait` endpoint because the transaction can fail when submitted, but the failure isn't manifested until a call to the `FuelGraphqlSubscriber.next` method is done. With this async instantiation, the subscription can be made to fail _before_ the actual subscription iterator is returned. I will add this failure handling in a subsequent PR that will tackle #2936, after I sync …
> chore!: wrap subscriptions in promise

- .changeset/great-boxes-scream.md
- packages/create-fuels/src/lib/setupProgram.ts
- Relates to #3004
We recently supported `vite` as a template for `create fuels`. Before making it the default template, we should also complete everything in #3004. This will fix the [failing integration test](https://github.com/FuelLabs/fuels-ts/actions/runs/10498760224/job/29099978488?pr=2991) in CI.
> chore: make `nextjs` the default `create fuels` template

- .changeset/fast-walls-report.md
- apps/docs-snippets/src/guide/predicates/interacting-with-predicates.test.ts
- apps/docs-snippets/src/guide/types/conversion.test.ts
- apps/docs-snippets/src/guide/wallets/checking-balances.test.ts
- packages/abi-coder/src/utils/getFunctionInputs.test.ts
- packages/abi-coder/src/utils/json-abi.test.ts
- packages/abi-coder/test/Interface.test.ts
- packages/abi-typegen/src/utils/makeFunction.test.ts
- packages/abi-typegen/src/utils/parseFunctions.test.ts
- packages/fuel-gauge/src/contract.test.ts
- packages/fuel-gauge/src/coverage-contract.test.ts
- packages/fuel-gauge/src/dry-run-multiple-txs.test.ts
- packages/fuel-gauge/src/fee.test.ts
- packages/fuel-gauge/src/generic-types-contract.test.ts
- packages/fuel-gauge/src/predicate-conditional-inputs.test.ts
- packages/fuel-gauge/src/raw-slice.test.ts
- packages/fuel-gauge/src/script-with-configurable.test.ts
- packages/fuel-gauge/src/script-with-vectors.test.ts
- packages/fuel-gauge/src/token-test-contract.test.ts
- packages/fuel-gauge/src/transaction-response.test.ts
- packages/fuel-gauge/src/transaction-summary.test.ts
- packages/fuel-gauge/src/vector-types.test.ts
- packages/fuel-gauge/src/vectors.test.ts
- packages/fuel-gauge/src/void.test.ts
There are way too many TS errors in the SDK's test files. This PR aims to cut down that number.
> chore: remove TS errors from some tests

- .changeset/strong-pears-walk.md
- Adds the missing changeset from #3035
> fix: added missing dependencies for templates

- .changeset/fast-ties-crash.md
- packages/utils/src/utils/bytecode.test.ts
- packages/utils/src/utils/bytecode.ts
- Closes #3039
- The compression of our bytecode is including a modified timestamp so the output of typegen is different in sequential runs. This PR fixes the modified timestamp to ensure the results of compression are equal.
- Showcase of [failure](https://github.com/FuelLabs/fuels-ts/actions/runs/10582459539/job/29322202973?pr=3040#step:6:1030) and success.
> fix: consistent typegen outputs

- .changeset/gentle-files-pay.md
- packages/account/src/providers/transaction-request/transaction-request.ts
- packages/contract/src/contract-factory.ts
- Deprecate the method `BaseTransactionRequest.fundWithFakeUtxos`
The method `BaseTransactionRequest.fundWithFakeUtxos` is being deprecated in favor of `Account.generateFakeResources`
```ts
// before
const baseAssetId = provider.getBaseAssetId();
const quantities = [{ amount: 100, assetId: baseAssetId }];
transactionRequest.fundWithFakeUtxos(quantities, baseAssetId, account.address);
```
```ts
// after
const baseAssetId = provider.getBaseAssetId();
const quantities = [{ amount: 100, assetId: baseAssetId }];
const fakeResources = account.generateFakeResources(quantities);
transactionRequest.addResources(fakeResources);
```
> chore: deprecate `BaseTransactionRequest.fundWithFakeUtxos`

- .changeset/wet-toes-switch.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
> feat: parse message response from `getMessageByNonce`

- .changeset/curvy-melons-itch.md
- packages/account/src/providers/transaction-request/blob-transaction-request.ts
- packages/account/src/providers/transaction-request/create-transaction-request.ts
- packages/account/src/providers/transaction-request/script-transaction-request.ts
- packages/account/src/providers/transaction-request/utils.test.ts
- Closes https://github.com/FuelLabs/fuels-ts/issues/3076
- We now return a deep clone of the transaction request in the static `from` method
I've applied this feat to the other `from` methods on the other `BaseTransactionRequest` subclasses
> feat: return deep clone on transaction request `from` method

- .changeset/tall-rivers-rest.md
- packages/account/src/providers/utils/extract-tx-error.ts
- packages/fuel-gauge/src/revert-error.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/revert-error/src/main.sw
- Closes #3099
This PR ensures that the correct Sway program logs are used whenever a transaction is reverted by the following validations:  `require`, `assert_eq`, and `assert_ne`.
> fix: assemble of transaction revert error message

- .changeset/hot-cats-happen.md
- packages/account/src/providers/provider.ts
- Fixed error handling in Provider for when a node is offline
If a node is offline, the Provider middleware throws an exception when it tries to inject the auth headers into an `undefined` request object, so we check if the `request` object is valid before injecting auth headers.
> fix: error handling in `Provider` for when a node is offline

- .changeset/grumpy-flies-sleep.md
- packages/contract/src/loader/loader-script.test.ts
- packages/contract/src/loader/loader-script.ts
- packages/fuel-gauge/src/contract-factory.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/proxy-contract/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/proxy-contract/src/main.sw
- Closes #3121
- Fixed an issue where you couldn't call a loader contract via a proxy contract
> fix: loader contract being called via proxy

- .changeset/long-ravens-explain.md
- packages/account/src/connectors/types/connector-types.ts
- Related https://github.com/FuelLabs/fuel-connectors/issues/237
- Add `signTransaction` method to `FuelConnectorMethods` enum 
This PR adds the `signTransaction` method to the [FuelConnectorMethods](https://github.com/FuelLabs/fuels-ts/blob/b063c6c4238d74f955810fc11768ec5e4a6dd9c5/packages/account/src/connectors/types/connector-types.ts#L1) enum. This ensures that the Fuel connector manager will correctly initialize any connector implementing this method during the execution of the [setupMethods](https://github.com/FuelLabs/fuels-ts/blob/b063c6c4238d74f955810fc11768ec5e4a6dd9c5/packages/account/src/connectors/fuel.ts#L204) function.
> feat: add `signTransaction` to `FuelConnectorMethods` enum

- .changeset/spicy-games-repeat.md
- apps/create-fuels-counter-guide/package.json
- apps/demo-wallet-sdk-react/package.json
- pnpm-lock.yaml
- templates/nextjs/package.json
- templates/vite/package.json
- templates/vite/src/sway-api/contract-ids.json
- Fixed transactions failing when using Ethereum and Solana connectors in the `create-fuels` template app
This PR bumps the `@fuels/connectors` and `@fuels/react` packages to `0.27.1`. This package bump fixes failing transactions when using Ethereum and Solana connectors in the `create-fuels` template app.
> chore: bump connectors package version

- .changeset/long-ravens-explain.md
- .changeset/tasty-geckos-train.md
- packages/account/src/connectors/types/connector-types.ts
- Closes #3148
- Closes TS-645
- Removed `signTransaction` method from `FuelConnectorMethods` enum
This PR reverts https://github.com/FuelLabs/fuels-ts/pull/3128.
> chore: revert add `signTransaction` to `FuelConnectorMethods` enum

- .changeset/fair-walls-smile.md
- packages/logger/test/index.test.ts
> Closes TS-659
- Closes #3192
> chore: adjust logger tests

- .changeset/small-readers-hug.md
- apps/docs/src/guide/wallets/connectors.md
- packages/account/src/connectors/fuel-connector.ts
- Added flag to indicate if connector is external
Add external flag to differentiate between native and external connectors.
N/A
> feat: add flag to indicate if connector is external

- .github/workflows/bench.yml
Temporarily disabled the benchmark workflow until it is fine-tuned.
> ci: temporarily disable benchmark workflow

- .github/workflows/linear-pr-integration.yaml
- Closes #3157 
This PR uses our [link-pr-to-linear-issues](https://github.com/FuelLabs/github-actions/tree/master/linear/link-pr-to-linear-issue) to... link PRs to Linear issues.
To review this, open up this PR's description to edit it and you'll see that the action added markdown comments at the beginning which do the deed.
> chore: link PRs with Linear issues

- .changeset/odd-starfishes-flash.md
- packages/account/package.json
- packages/account/src/test-utils/launchNode.ts
- pnpm-lock.yaml
This PR replaces the `portfinder` dependency with the ephemeral port `0` via which the OS is given reins to assign whichever free port it sees fit.
This PR should stop the [flakiness](https://github.com/FuelLabs/fuels-ts/actions/runs/11059718909/job/30728669902) that occurs because of trying to start a node on a port that's already in use. I believe that the underlying cause of this is that the free port number given by `portfinder` gets taken by a different node in some other test before the flaky test's node starts. By using port `0`, the real port is only given to the `fuel-core` node by the OS upon starting of the node, so conflicts like these won't happen.
> fix: reduce flakiness by favoring port `0` over `portfinder` dependency

- .changeset/popular-bikes-allow.md
- packages/fuels/src/cli/commands/deploy/proxy/types/Src14OwnedProxy.ts
- packages/fuels/src/cli/commands/deploy/proxy/types/Src14OwnedProxyFactory.ts
- packages/fuels/src/cli/commands/deploy/proxy/types/common.d.ts
- packages/fuels/src/cli/commands/deploy/proxy/types/index.ts
- scripts/changeset/changeset-version-with-docs.ts
The last release [failed silently](https://github.com/FuelLabs/fuels-ts/actions/runs/11061528093/job/30734321051#step:11:33) halfway — packages were published, but the GitHub tag/release wasn't created.
This happened because some new `typegen` generated files were added during `build` (via https://github.com/FuelLabs/fuels-ts/pull/3190).
This PR accounts for these files.
> chore: regenerate proxy artifacts during release

- .changeset/serious-crabs-begin.md
- .knip.json
- packages/account/package.json
- packages/account/scripts/generate-fuel-core-schema.mts
- packages/account/test/fuel-core-schema.test.ts
- Closes #2938 
The `build:schema` script now starts and kills its own node, thereby not depending on a node running on port `4000`.
> chore: make `build:schema` script self-sufficient

- .eslintignore
- .prettierrc
- apps/docs-snippets2/scripts/wrap-snippets.ts
- apps/docs/nodemon.config.json
This PR introduces minor adjustments to the new infrastructure for documentation code snippets.
> docs: adjustments to new doc snippets infra

- .changeset/angry-buses-jam.md
- .github/workflows/bench.yml
Post-merge of https://github.com/FuelLabs/fuels-ts/pull/3166 we should get more reliable benchmark runs given we have more iterations to reduce variance. The PR re-enables the benchmarks so that we can track those runs against local nodes.
> ci: re-introduce benchmarks on PRs

- nodemon.config.json
- packages/contract/src/contract-factory.ts
- packages/fuels/src/cli/commands/deploy/deployScripts.ts
- packages/fuels/src/cli/commands/deploy/index.ts
- packages/fuels/src/cli/commands/deploy/saveScriptFiles.ts
- packages/fuels/src/cli/config/forcUtils.ts
- packages/fuels/src/cli/types.ts
> feat: implement predicates/scripts CLI deploy

- packages/abi/src/matchers/sway-type-matchers.test.ts
- packages/abi/src/matchers/sway-type-matchers.ts
- Adds missing `str` matcher to the sway type matchers.
- Enables `name` to be extracted from the `Struct` and `Enum` regex.
- Fixed issue whereby if a matcher was `undefined`, then it wouldn't be found.
> feat: add missing matcher

- .changeset/filthy-bacteria-multiply.md
- packages/account/src/providers/operations.graphql
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- Part of #3281 
This PR adds a new `getChainAndNodeInfo` query which returns the `chain` and `nodeInfo` data in one request, as opposed to the way we've been doing up until now where we've been sending them separately.
> chore: merge `chain` and `nodeInfo` queries into one

- .changeset/tame-gorillas-shave.md
- packages/account/src/providers/operations.graphql
- Closes #3293
- Optimised the provider balance queries
- Removed the `owner` and `assetId` properties from the response of `Provider.operations.getBalance()`. These properties are also required arguments to execute the function so are redundant in the response. Should you require these values, you should take them from the values that you passed to the function.
- Removed the `owner` property from the response of `Provider.operations.getBalances()`. This property is a required argument to execute the function so is redundant in the response. Should you require this value, you should take it from the value that you passed to the function.
> chore!: optimize balance queries

- .changeset/thick-rocks-hammer.md
- apps/docs-snippets/src/guide/provider/querying-the-chain.test.ts
- apps/docs/src/guide/provider/querying-the-chain.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- Closes #3245 
- Added a limit of 30 transactions to the `provider.getTransactions()` method.
> feat: add pagination limit to `getTransactions`

- .changeset/fluffy-pears-search.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
Bumps the transaction pagination limit. I should've used this value in #3304.
> feat: bump transaction pagination limit to 60

- .changeset/hip-files-protect.md
- .github/workflows/pr-release.yaml
- packages/address/src/address.test.ts
- packages/address/src/address.ts
- packages/interfaces/src/index.ts
- We add a checksum utils to the Address class that provides the ability to encode an address into a valid checksum HEX address and add a verification function to validate the encoded checksum HEX address.
```ts
import { Address } from 'fuels';
const address = Address.fromRandom();
const checksumAddress = address.toChecksum();
console.log(Address.isChecksumValid(address));
```
> feat: add checksum utils for address

- .changeset/good-pants-chew.md
- apps/docs-snippets/src/guide/types/address.test.ts
- packages/address/src/address.test.ts
- packages/address/src/address.ts
- Made `Address.toString` and `Address.valueOf` returns the Address checksum
The return of both `Address.toString()` and `Address.valueOf` was modified to return the address checksum instead of the Bech32 string
```ts
// before
const address = new Address('fuel1elnmzsav56dqnp95sx4e2pckq36cvae9ser44m5zlvgtwxw49fmqd7e42e');
address.toString()
// fuel1elnmzsav56dqnp95sx4e2pckq36cvae9ser44m5zlvgtwxw49fmqd7e42e
address.valueOf()
// fuel1elnmzsav56dqnp95sx4e2pckq36cvae9ser44m5zlvgtwxw49fmqd7e42e
```
```ts
// after
const address = new Address('fuel1elnmzsav56dqnp95sx4e2pckq36cvae9ser44m5zlvgtwxw49fmqd7e42e');
address.toString()
// 0xEf86aFa9696Cf0dc6385e2C407A6e159A1103cEfB7E2Ae0636FB33d3cb2A9E4A
address.valueOf()
// …
```
> chore!: made Address `toString` and `valueOf` returns checksum

- .changeset/pink-walls-greet.md
- apps/docs-snippets/src/guide/types/address.test.ts
- packages/address/src/address.test.ts
- packages/address/src/address.ts
- Fixed checksum utility to correctly remove `0x` before hashing
We fixed the checksum utilities:
- `Address.toChecksum()`
- `Address.isChecksumValid()`
Now, we correctly remove the leading `0x` before hashing the address.
Because of this, previous values were invalid, and the update is required.
> fix!: checksum method to remove `0x` before hashing

- .changeset/tidy-scissors-sip.md
- packages/math/src/bn.test.ts
- packages/math/src/bn.ts
- Closes #3316
- Fixed a bug where `bn.parseUnits` wouldn't work as expected with `units = 0`
This PR fixes a bug in `bn.parseUnits`, as a follow-up of #3300.
> fix: `parseUnits` bug with 0 units

- .changeset/ten-dryers-search.md
- packages/address/src/address.ts
> chore: use `FuelError` instead of JS `Error`

- .changeset/breezy-experts-trade.md
- packages/create-fuels/package.json
- pnpm-lock.yaml
- Fixing [failing integration test](https://github.com/FuelLabs/fuels-ts/actions/runs/11446004965/job/31844264521?pr=3347#step:6:94).
- The package `@fuel-ts/version` is required for running the `create-fuels` CLI:
https://github.com/FuelLabs/fuels-ts/blob/722ccde23382d0cf5875a501115c0cf4a549b3e1/packages/create-fuels/src/cli.ts#L128
- Currently, we have `@fuel-ts/version` installed as a dev dependencies, so:
- We publish the templates for `create-fuels` with the following package.json `"fuels": "0.96.2"` (the dev dependency version)
- Then attempt to replace with the `0.96.1` (the previous version)
- I investigated the published versions on NPM to get this outcome.
-  Working version: [0.0.0-next-20241021144504](https://www.npmjs.com/package/create-fuels/v/0.0.0-next-20241021144504?active …
> fix: moved `create-fuels` deps for `fuels-ts`

- .changeset/orange-panthers-lay.md
- packages/fuel-gauge/src/advanced-logging.test.ts
- packages/fuel-gauge/src/predicate/predicate-configurables.test.ts
We missed some fuel-gauge tests when we moved to dogfooding typegen outputs, which this PR fixes.
> chore: use typegen'd outputs in some fuel-gauge tests

- .changeset/khaki-teachers-study.md
- packages/account/package.json
- packages/account/src/providers/provider.ts
- pnpm-lock.yaml
- Closes #2567
Upgrades a major version of `graphql-request`. It is actually currently at `v7` with `v8` coming very soon. I have discussed why we can't upgrade that high [here](https://github.com/FuelLabs/fuels-ts/issues/2567#issuecomment-2514285115).
> chore: upgrade `graphql-request@6.1.0`

- .changeset/afraid-ligers-work.md
- packages/recipes/package.json
Silences the prettier log output for the recipes package to reduce noise on build.
> chore: silence recipes format logs

- .github/workflows/test.yaml
- apps/create-fuels-counter-guide/package.json
- package.json
- pnpm-lock.yaml
- templates/nextjs/package.json
- templates/vite/package.json
- vitest.browser.config.mts
Vitest now [recommends](https://vitest.dev/guide/browser/#manual-installation) running browser tests with playwright because of parallel execution capabilities:
> If you don't already use one of these tools, we recommend starting with Playwright because it supports parallel execution, which makes your tests run faster. Additionally, the Chrome DevTools Protocol that Playwright uses is generally faster than WebDriver.
We get a 2-3 minute speed-up in browser tests with this change ([before](https://github.com/FuelLabs/fuels-ts/actions/runs/12319828961/job/34387779085), [now](https://github.com/FuelLabs/fuels-ts/actions/runs/12571326373/job/35042116724?pr=3515)). I expected a larger speed-up given that it parallelizes the tests, though. There might be some configuration missing but I didn't …
> chore: use playwright in browser tests

- .changeset/shaggy-zebras-obey.md
- apps/docs/src/guide/cookbook/snippets/custom-contract-calls.ts
- apps/docs/src/guide/cookbook/snippets/signing-transactions/predicate.ts
- apps/docs/src/guide/encoding/snippets/encode-and-decode.ts
- apps/docs/src/guide/predicates/snippets/custom-transactions.ts
- apps/docs/src/guide/predicates/snippets/methods/send-transaction.ts
- apps/docs/src/guide/predicates/snippets/methods/simulate-transaction.ts
- apps/docs/src/guide/scripts/snippets/script-custom-transaction.ts
- apps/docs/src/guide/transactions/snippets/transaction-request/auto-cost.ts
- apps/docs/src/guide/transactions/snippets/transaction-response/from-submitted-request.ts
- apps/docs/src/guide/transactions/transaction-request.md
- apps/docs/src/guide/wallets/snippets/signing/fund-transaction.ts
- apps/docs/src/guide/wallets/snippets/signing/sign-transaction.ts
- packages/account/src/account.test.ts
- packages/account/src/providers/transaction-request/script-transaction-request.ts
- packages/fuel-gauge/src/advanced-logging.test.ts
- packages/fuel-gauge/src/contract.test.ts
- packages/fuel-gauge/src/coverage-contract.test.ts
- packages/fuel-gauge/src/fee.test.ts
- packages/fuel-gauge/src/funding-transaction.test.ts
- packages/fuel-gauge/src/policies.test.ts
- packages/fuel-gauge/src/predicate/utils/predicate/fundAccount.ts
- packages/fuel-gauge/src/revert-error.test.ts
- packages/fuel-gauge/src/transaction-response.test.ts
- packages/fuel-gauge/src/transaction-summary.test.ts
- packages/fuel-gauge/src/transaction.test.ts
- packages/program/src/functions/base-invocation-scope.ts
- packages/script/src/script.test.ts
- Closes #3535
- Added the `autoCost` method to easily estimate and fund transactions
- Migrated `fundWithRequiredCoins` -> `autoCost` for contract and script calls
Added a helper method to the `ScriptTransactionRequest` to easily estimate and fund a transaction. This allows consumers to easily bundle transactions before submission. This will form part of the _optimisation_ docs in #3535.
```ts
// before
const txCost = await wallet.getTransactionCost(request);
request.gasLimit = txCost.gasUsed;
request.maxFee = txCost.maxFee;
await wallet.fund(request, txCost);
// after
await request.autoCost(wallet);
```
To be brought inline with `autoCost`, funding a contract and script call has been migrated from `fundWithRequiredCoins` to `autoCost`:
```ts
// before
const request: …
```
> feat!: `autoCost` for transaction estimation and funding

- .changeset/shiny-meals-jog.md
- packages/account/src/providers/operations.graphql
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- packages/fuel-gauge/src/transaction-response.test.ts
- Closes #3518 
This PR removes the `submitAndAwait` operation which was previously deprecated.
- `submitAndAwait` operation was removed
After being deprecated since #3101, we have removed this operation altogether. Please use the `submitAndAwaitStatus` method instead which gives the same results as `submitAndAwait`. If you are interested in the deprecation/removal reasons, please refer to https://github.com/FuelLabs/fuel-core/issues/2108.
```ts
// before
const response = await provider.operations.submitAndAwait(txRequest);
```
```ts
// after
const response = await provider.operations.submitAndAwaitStatus(txRequest);
```
> chore!: remove deprecated `submitAndAwait` operation

- .changeset/small-spoons-drive.md
- .github/workflows/pr-release.yaml
- apps/create-fuels-counter-guide/src/components/Faucet.tsx
- apps/create-fuels-counter-guide/src/components/Predicate.tsx
- apps/create-fuels-counter-guide/src/components/Wallet.tsx
- apps/create-fuels-counter-guide/src/hooks/useBaseAssetId.tsx
- templates/nextjs/src/components/Faucet.tsx
- templates/nextjs/src/components/Predicate.tsx
- templates/nextjs/src/components/Wallet.tsx
- templates/nextjs/src/hooks/useBaseAssetId.tsx
- templates/vite/src/components/Faucet.tsx
- templates/vite/src/components/Predicate.tsx
- templates/vite/src/components/Wallet.tsx
- templates/vite/src/hooks/useBaseAssetId.tsx
- Fix [failing](https://github.com/FuelLabs/fuels-ts/actions/runs/12635048842/job/35204125857) integration tests
- Due to the breaking changes in #3509, the [`useBalance`](https://github.com/FuelLabs/fuel-connectors/blob/d9c06243c092313a331228a081a0c5f722905234/packages/react/src/hooks/useBalance.ts#L62) hook was not obtaining the `baseAssetId` correctly.
```bash
$ PUBLISHED_NPM_TAG=pr-3550 sh ./scripts/tests-ui-integration.sh
Running 2 tests using 2 workers
2 passed (10.7s)
```
> chore: added `useBaseAssetId` hook to templates

- .changeset/strange-experts-roll.md
- apps/docs/src/guide/getting-started/snippets/connecting-to-the-network.ts
- apps/docs/src/guide/transactions/snippets/transaction-request/auto-cost.ts
- packages/account/src/providers/provider.ts
Quick follow-up after:
- https://github.com/FuelLabs/fuels-ts/pull/3514
Ultimately, the breaking changes were inevitable, so there's no point in keeping a deprecated method.
> chore: removing obsolete `Provider.create` method

- README.md
- apps/docs/src/guide/contracts/using-different-wallets.md
- apps/docs/src/guide/getting-started/cdn-usage.md
- apps/docs/src/guide/getting-started/react-example.md
Follow-up after:
- https://github.com/FuelLabs/fuels-ts/pull/3514
- https://github.com/FuelLabs/fuels-ts/pull/3556
> docs: fixing remaining outdated snippets

- .changeset/ten-cherries-perform.md
- .github/workflows/pr-release.yaml
- templates/vite/tailwind.config.ts
- Favour TS config files over JS for Tailwind in the Vite template
- In relation to the [forum post](https://forum.fuel.network/t/es-module-problem/7994)
> chore: changed Tailwind config from JS to TS

- .changeset/nasty-carrots-report.md
- packages/abi-coder/src/FunctionFragment.ts
- packages/fuel-gauge/src/abi/abi-script.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/script-with-complex-args/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/script-with-complex-args/src/main.sw
- Closes #3587 
- Fixed incorrect offset usage for `Interface.decodeArguments` function.
> fix: incorrect function coder offset usage

- .changeset/wet-goats-push.md
- .github/workflows/pr-lint.yaml
- CONTRIBUTING.md
Updated commit conventions to align with the `CONTRIBUTING.md` guidelines. Removed the `rc` convention.
> chore: adjust commit conventions

- .changeset/young-queens-juggle.md
- .github/workflows/code-lint.yaml
- Closes #3596 
- Set the `timeout-minutes` for CI jobs:  **30** minutes for `lint`, enhancing build efficiency and preventing excessive runtime
> ci: configure timeout for docs and lint jobs

- .changeset/clever-mirrors-jam.md
- packages/account/src/account.ts
- packages/account/src/providers/provider.ts
- packages/fuel-gauge/src/fee.test.ts
- packages/program/src/functions/base-invocation-scope.ts
- Allowed passing `gasPrice` to `getTransactionCost` functions to reduce possible network calls
In the Fuel Wallet, a user can set a custom gas limit or tip for a transaction. It then checks if that changes the fee. If it has, it will re-estimate and fund the transaction. 
This leads to two gas price fetches. One in the initial fee calculation, and one in the re-estimation. 
By allowing the `getTransactionCost` to take a `gasPrice` parameter, we can reduce the number of network calls for this flow.
The expected flow could then look like so:
```ts
// Some user input that could change the fee
const tip = userInput.tip;
transactionRequest.tip = tip;
// Calculate the new fee, also fetches and returns the gas price
const { maxFee, gasPrice } = await …
```
> feat: allow passing `gasPrice` to `getTransactionCost`

- .changeset/soft-poems-reflect.md
- apps/create-fuels-counter-guide/src/components/LocalFaucet.tsx
- apps/docs/src/guide/types/b256.md
- apps/docs/src/guide/wallets/wallet-transferring.md
Using `new Address` on docs instead of deprecated methods
> docs: use `new Address` in favor of deprecated method

- .changeset/stupid-owls-worry.md
- packages/abi-coder/package.json
- packages/contract/package.json
- packages/transactions/package.json
- pnpm-lock.yaml
- Closes #3632 
- Adjusted workspace version resolution to a fixed version
> chore: fix version resolutions

- .changeset/plenty-beds-bake.md
- .github/workflows/release.yaml
- apps/docs/src/guide/wallets/snippets/connectors.ts
- packages/account/src/providers/assets/assets.test.ts
- packages/account/src/providers/assets/utils/fuelAssetsBaseUrl.ts
- packages/account/src/providers/assets/utils/network.test.ts
- packages/fuel-gauge/src/e2e-script.test.ts
- Migrated CDN host from `cdn.fuel.network` to `assets.fuel.network`
This PR updates the GitHub release workflow to publish to our assets CDN endpoint. It also migrates the flow to using OIDC-based AWS authentication instead of static access keys.
> fix: s3 publishing

- .github/workflows/release.yaml
This PR updates the values in the GitHub release workflow to source values from GitHub variables and not environment variables.
> fix: use GitHub vars instead of env vars

- .changeset/big-dragons-count.md
- packages/account/src/providers/operations.graphql
- packages/account/src/providers/provider.test.ts
- Closes #3651
- Removed `pageInfo` from `provider.operations.getBalances` response
The `pageInfo` field has been removed from the response of the `provider.operations.getBalances` query.
```ts
// before
const { balances, pageInfo } = await provider.operations.getBalances({
first: 100,
filter: { owner: wallet.address.toB256() },
});
```
```ts
// after
const { balances } = await provider.operations.getBalances({
first: 100,
filter: { owner: wallet.address.toB256() },
});
```
The `getBalances` method of the Provider class remains unchanged, as it never returned pageInfo:
```ts
// not affected
const { balances } = await provider.getBalances();
```
> chore!: remove `pageInfo` from `getBalances` GraphQl operations

- .changeset/brown-chairs-tickle.md
- packages/account/src/providers/transaction-response/transaction-response.ts
- packages/fuel-gauge/src/advanced-logging.test.ts
- packages/fuel-gauge/src/await-execution.test.ts
- packages/fuel-gauge/src/doc-examples.test.ts
- packages/fuel-gauge/src/min-gas.test.ts
- packages/fuel-gauge/src/predicate/predicate-populate-witness.test.ts
- packages/fuel-gauge/src/str-slice.test.ts
- packages/fuel-gauge/src/transaction-response.test.ts
- packages/fuel-gauge/src/transaction.test.ts
- Closes #3659
- Fixed a de-structuring issue when calling `waitForResult` on a submitted transaction
- Binds `waitForResult` to the `TransactionResponse` to defend against de-structuring problems
- Added result de-structuring to a few different tests
> fix: bind `waitForResult` in `TransactionResponse`

- .changeset/curly-brooms-flash.md
- packages/account/src/providers/operations.graphql
- packages/account/src/providers/provider.ts
- packages/account/src/providers/transaction-request/helpers.test.ts
- packages/account/src/providers/transaction-request/helpers.ts
- packages/fuel-gauge/src/fee.test.ts
- packages/fuel-gauge/src/predicate/predicate-estimations.test.ts
- Closes #3675
- Merge gas price and predicate estimation on a single request
> chore: merge gas price and predicate estimation requests

- .changeset/curvy-peaches-wonder.md
- apps/create-fuels-counter-guide/package.json
- apps/demo-react-vite/package.json
- package.json
- packages/abi-typegen/test/utils/getNewAbiTypegen.ts
- packages/account/src/assets/asset-api.test.ts
- packages/account/src/test-utils/launchNode.test.ts
- packages/create-fuels/src/lib/installFuelUp.test.ts
- packages/create-fuels/src/utils/logger.test.ts
- packages/errors/src/test-utils/expect-to-throw-fuel-error.ts
- packages/fuels/package.json
- packages/fuels/src/cli/commands/build/buildSwayProgram.test.ts
- packages/fuels/src/cli/utils/logger.test.ts
- packages/utils/package.json
- packages/versions/src/lib/getSystemVersions.test.ts
- pnpm-lock.yaml
- templates/nextjs/package.json
- templates/vite/package.json
- Upgraded `vite` related dependencies
| Dependency                  | Version |
| --------------------------- | ------- |
| `vite`                      | 6.1.0   |
| `vitest`                    | 3.0.5   |
| `@vitest/browser`           | 3.0.5   |
| `@vitest/coverage-istanbul` | 3.0.5   |
> chore: upgrade `vite` related dependencies

- .changeset/silent-points-punch.md
- packages/account/src/providers/fuel-graphql-subscriber.ts
- packages/account/src/providers/provider.test.ts
- Closes #3684
Fuel network logs showed some subscriptions weren't being closed and the current hypothesis is that the TS SDK is the culprit because it doesn't automatically read data as it comes from the node but rather waits for the user to start reading it. Even though the fuel-core nodes do close subscriptions once they stream all the data, they still have to wait for ACK messages from the clients and it might be the case that sometimes the clients' TCP receive buffer gets filled up to the point that they stop sending ACK messages to the server (because they don't read the stream), putting the server in a stalemate position until it kills the subscription via timeouts.
The next step would be to integrate the `submit` mutation ergonomically via
- #3683 
so that users can decide to not …
> fix: ignored subscriptions not being read

- .changeset/shaggy-ravens-switch.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- Closes #3692
- Made `getBlockWithTransactions` and `getBlock` supports BN paramter
> chore: support BN input in block fetch methods

- .changeset/nine-bats-fail.md
- packages/account/src/providers/transaction-summary/call.ts
- packages/account/src/providers/transaction-summary/operations.ts
- packages/fuel-gauge/src/transaction-summary.test.ts
- Part of #3733
Removes some of the work introduced by #3704 but ensures the `abiMap` param still does not throw (#3703). #3710 proposed a way to introduce multi call operations, but the solution in #3733 is more robust. This PR sets the stage for #3733.
> chore: remove call ops in tx summary

- packages/account/src/account.ts
- packages/account/src/connectors/types/data-type.ts
- packages/account/src/providers/provider.ts
- packages/account/src/providers/transaction-request/transaction-request.ts
- packages/account/src/providers/utils/serialization.ts
- packages/account/test/fuel-wallet-connector.test.ts
- Part of #3669
Uses receipts from estimation in tandem with the current logic around transaction state to pass a partial transaction summary via JSON RPC to the wallet. A full summary can then be assembled via `assembleTransactionSummaryFromJson()`.
> feat: add tx summary to send tx JSON RPC

- .changeset/solid-roses-battle.md
- internal/forc/lib/shared.js
- internal/fuel-core/lib/shared.js
Fixes `ERR_FS_CP_NON_DIR_TO_DIR` error when installing from `git:` branches.
> fix: `fuel-core` and `forc` git branch installation error

- .github/workflows/changesets-pr.yaml
- .github/workflows/release.yaml
Fixes `changesets-pr` and `release` workflow conditional.
> ci(release): fix release `v0.100.0`

- .changeset/nice-camels-marry.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/provider.ts
- Closes #3766
- Eliminated duplicate chain requests across multiple concurrent provider instances
- Multiple instances of a provider could request the chain info simultaneously, causing the cached values to be missing. This ensures that only a single request is made across multiple provider instances.
> chore: eliminate chain requests across concurrent provider instances

- .changeset/fancy-cooks-doubt.md
- packages/account/src/providers/transaction-response/getDecodedLogs.ts
- packages/fuel-gauge/src/advanced-logging.test.ts
- packages/fuel-gauge/test/fixtures/forc-projects/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/script-call-logging-contracts/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/script-call-logging-contracts/src/main.sw
- packages/program/src/functions/base-invocation-scope.ts
- Closes #3789
- Closes #3780
- Avoid decoding logs from inter-called contracts without a JSON ABI
> fix: skip decoding external contract logs without JSON ABI

- .changeset/bright-sides-camp.md
- .github/workflows/publish-to-next.yaml
- .github/workflows/release.yaml
We lost the `pr`/`next` release message when we deleted the old pr release workflow in #3735, that message is still useful.
> chore: add pr release message

- .github/workflows/changesets-pr.yaml
Fixes wrong `changesets-pr` workflow condition.
> fix: `changesets-pr` workflow condition

- apps/docs/src/guide/wallets/connectors.md
- packages/account/test/fixtures/mocked-send-transaction-connector.ts
- packages/account/test/fuel-wallet-connector.send-transaction.test.ts
- packages/fuel-gauge/src/connectors.test.ts
- packages/fuel-gauge/test/fixtures/connectors/mock-connector.ts
- packages/fuel-gauge/test/fixtures/connectors/mock-predicate-connector.ts
- packages/fuel-gauge/test/fixtures/connectors/mock-predicate-signer-connector.ts
- packages/fuel-gauge/test/fixtures/connectors/mock-solana-connector.ts
- packages/fuel-gauge/test/fixtures/forc-projects/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/predicate-sol/Forc.toml
- packages/fuel-gauge/test/fixtures/forc-projects/predicate-sol/src/main.sw
- Closes #3665
- Enabled a snappier transaction summary generation for connectors
In #3669 we altered the connector `sendTransaction` signature to now return `string | TransactionResponse`:
https://github.com/FuelLabs/fuels-ts/blob/e8494fa488848ba215e339e2dd12364ab5b3a1a1/packages/account/src/connectors/fuel-connector.ts#L47-L51
This approach enables #3665 to enable connector transactions to submit and generate a transaction summary in apps in a single request.
This PR enforces this approach in tests and docs so that in can be implemented by connectors.
> We may look to introduce another approach (such as that proposed by #3761) that encourages the Fuel Wallet to utilise this flow, however for now the above will enable non-native connectors.
> feat: inverted submission flow

- .changeset/quick-moments-change.md
- apps/docs-api/typedoc.json
- apps/docs/package.json
- apps/docs/scripts/clear-snippets.mts
- packages/fuels/src/cli/commands/build/buildSwayProgram.test.ts
- packages/fuels/src/cli/commands/build/buildSwayProgram.ts
- packages/fuels/src/cli/commands/init/index.ts
- packages/fuels/test/features/init.test.ts
- vitest.browser.config.mts
- Made `docs` `build:forc` command silent, so the CLI output is less noisy
- Fixed incorrect logger usage in `fuels`
- Suppress warning errors from `docs-api`
- We get 200+ warnings, but unable to see the errors, now it's easier to see the errors.
- Added command to delete all `*.test.ts` files from the docs
- Allows for switching branches and errors not occurring with previous test files
- Suppress screenshots from `vitest`
> chore: various fixes for suppressing build noise

- apps/docs/src/guide/getting-started/cdn-usage.md
- Close #3856
- Switched CDN provider from `cdnjs` to `jsdelivr`
> chore: switching from `cdnjs` to `jsdelivr`

- apps/docs/src/guide/wallets/mnemonic-wallet.md
Fixing the default derivation path in Wallet mnemonic docs.
> docs: fixing the default derivation path in Wallet mnemonic docs

- apps/docs/src/guide/testing/fuel-core-options.md
- link-check.config.json
Adjusted `retryOptions` to fix [GH rate-limit issue](https://www.google.com/search?q=markdown-link-check+status+429+github+links&oq=markdown-link-check+status+429+github+links&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDU4MzZqMGoxqAIAsAIA&sourceid=chrome&ie=UTF-8).
> fix: ci md-links check

- .changeset/nine-games-arrive.md
- packages/account/src/account.ts
- packages/account/src/connectors/fuel-connector.ts
- packages/account/src/providers/transaction-request/transaction-request.ts
- packages/account/src/providers/transaction-response/transaction-response.ts
- packages/account/src/providers/utils/transaction-response-serialization.test.ts
- packages/account/src/providers/utils/transaction-response-serialization.ts
- packages/account/test/fixtures/mocked-connector.ts
- packages/account/test/fixtures/mocked-send-transaction-connector.ts
- Closes #3877
- Implemented helpers to serialize/deserialize `TransactionResponse`
> feat: implement methods to serialize/deserialize `TransactionResponse`

- .changeset/cyan-oranges-smash.md
- packages/account/src/account.ts
- packages/account/src/connectors/fuel-connector.ts
- packages/account/src/providers/index.ts
- packages/account/src/providers/utils/transaction-response-serialization.ts
- packages/account/test/fixtures/mocked-connector.ts
- packages/account/test/fixtures/mocked-send-transaction-connector.ts
- Made connector `sendTransaction` return `TransactionResponse` instead `TransactionResponseJson`
> chore: made connector returns `TransactionResponse` type

- .changeset/rare-kids-grab.md
- packages/account/src/providers/provider.test.ts
- packages/account/src/providers/transaction-response/transaction-response.ts
- Closes #3888
- Close subscription after `Preconfirmation` when another status is not awaited by the user
> fix: close subscription after `Preconfirmation` status when applicable

- .changeset/loud-bags-deny.md
- apps/create-fuels-counter-guide/src/components/Predicate.tsx
- apps/docs/src/guide/predicates/snippets/deploying-predicates.ts
- packages/account/src/predicate/predicate.ts
- packages/fuel-gauge/src/blob-deploy.test.ts
- packages/fuel-gauge/src/predicate/predicate-configurables.test.ts
- packages/fuel-gauge/src/predicate/predicate-estimations.test.ts
- packages/fuel-gauge/src/predicate/predicate-invalidations.test.ts
- templates/nextjs/src/components/Predicate.tsx
- templates/vite/src/components/Predicate.tsx
- Closes #3771
- Closes #1552
- Enforced Predicate's `data` property when the Predicate has arguments
Predicates that define arguments must now be instantiated with the data property. It is no longer allowed to omit data when the predicate expects input arguments.
For example, for the given predicate:
```rs
predicate;
fn main(pin: u64) -> bool {
return 999 == pin;
}
```
The following code would compile, even though the predicate expects arguments:
```ts
// before
const predicateNoData = new PredicatePin({ provider }) // ✅ Allowed (incorrectly)
const predicate = new PredicatePin({ provider, data: [100] }) // ✅ Correct
```
TypeScript now enforces that data must be provided:
```ts
// after
const predicateNoData = new PredicatePin({ provider }) // ❌ Error: missing …
```
> fix!: enforce `predicateData` when predicate has arguments

- .changeset/fresh-kings-matter.md
- .github/workflows/test.yaml
- package.json
- packages/abi-coder/package.json
- packages/abi-typegen/package.json
- packages/account/package.json
- packages/address/package.json
- packages/contract/package.json
- packages/create-fuels/package.json
- packages/crypto/package.json
- packages/errors/package.json
- packages/fuels/package.json
- packages/hasher/package.json
- packages/logger/package.json
- packages/math/package.json
- packages/merkle/package.json
- packages/program/package.json
- packages/recipes/package.json
- packages/script/package.json
- packages/transactions/package.json
- packages/utils/package.json
- packages/versions/package.json
- Related to #3524 
- Deprecated Node 18 - upgrade to a newer version of Node.
Removed support for Node 18 due to the version no longer being maintained.
> chore: support Node 24 - depreciate Node 18

- .changeset/cyan-pandas-know.md
- packages/account/src/providers/utils/extract-tx-error.ts
- packages/fuel-gauge/src/revert-error.test.ts
- Added the JSON ABI error entry to `FuelError.metadata` property
> chore: add JSON ABI error entry to `FuelError.metadata`

- .github/workflows/release.yaml
Missed some envs for the release workflow to allow for Vercel to be deployed
> fix: added missing envs for Vercel release

- .changeset/hungry-clouds-switch.md
- Breaking change for the following PR:
- #3901 
- `fuel-core` release [`v0.44.0`](https://github.com/FuelLabs/fuel-core/releases/tag/v0.44.0) is a breaking change.
> chore!: breaking change for `fuel-core@v0.44.0`

- .changeset/beige-days-listen.md
- .gitignore
- packages/contract/src/contract-factory.ts
- packages/fuel-gauge/src/contract-factory.test.ts
ContractFactory.createTransactionRequest allows to pass configurableConstants, but does not use them. It is both confusing because the default ones will be used, and because the returned contract ID will not match with the one returned by the deploy method, which uses the configurables.
> fix: configurables constants on createTransactionRequest not been set
